### ISSUE TITLE
Create HTML table component

### ISSUE THREAD

**Issue by coopy** [plotly/dash-core-components#10]

**Comment by priyankt68** [comment]
@coopy Can I work on this ?

I have setup development environment and I believe we would need to add ```table``` component as [React Table component (rc-table)](https://github.com/react-component/table).

**Comment by chriddyp** [comment]
@priyankt68 - PRs accepted! You can also create your own plugins by following the instructions at https://plot.ly/dash/plugins. There is also some prototyping work being done here: https://github.com/plotly/dash-table-experiments
