### ISSUE TITLE
selectedData callback not firing with parcoords plot

### ISSUE THREAD

**Issue by slishak** [plotly/dash-core-components#101]
I saw in the Dash documentation a suggestion to use parallel coordinates plots [here](https://plot.ly/dash/interactive-graphing), which looks like a great way to filter data. However when selecting data on this plot the selectedData callback never fires so I can't link it to other plots.

**Comment by chriddyp** [comment]
Thanks for reporting! I just added a note about this here: https://github.com/plotly/plotly.js/issues/170

**Comment by slishak** [comment]
This is fixed by https://github.com/plotly/dash-core-components/pull/483!
