### ISSUE TITLE
'module' object has no attribute 'Tabs'

### ISSUE THREAD

**Issue by rnmourao** [plotly/dash-core-components#124]
`app.layout = html.Div([
     dcc.Tabs(
        tabs=[
            {'label': 'Cargos', 'value': 'idx-cargo'},
            {'label': 'Calculadora de TV', 'value': 'idx-calc'},
            {'label': 'Eficiência dos Partidos', 'value': 'idx-bolhas'},
            {'label': 'Perfil do Candidato', 'value': 'idx-perfil'},
            {'label': 'Capital Eleitoral', 'value': 'idx-capital'}
        ],
        value='idx-cargo',
        id='tabs'
    ),
    html.Div(id='page-content')
])`

The message is:

> Traceback (most recent call last):
  File "index.py", line 12, in <module>
    dcc.Tabs(
AttributeError: 'module' object has no attribute 'Tabs'

I didn't see a Tabs.react.js module on version 15.2...

**Comment by chriddyp** [comment]
Tabs isn't released yet, please see https://github.com/plotly/dash-core-components/pull/74

**Comment by rnmourao** [comment]
Ok, thanks!
