### ISSUE TITLE
Difficulty emulating vanilla anchor tags with dcc.Link 

### ISSUE THREAD

**Issue by ned2** [plotly/dash-core-components#129]
The `dcc.Link` component renders as `<a>` tags without an `href` attribute, since the routing is all taken care of in the React side of things. This means that out of the box these links don't receive the default linkified browser styles of underline and pointer cursor on hover etc as well as the browser providing a preview of the link address in the bottom left corner. It would be nice to have this behaviour.

The styles can be emulated through custom CSS but not the href preview on hover. I've tried working around this by using an anchor tag within the `dcc.Link` like this:

```python
href = '/some-path'
dcc.Link(html.A(text, href=href), href=href)
```
All the styles and hover behaviour works as expected, but the problem is that when clicking on the link, in addition to Dash handling the `dcc.Link`'s callback, the nested `<a>` also gets a click event which then causes a whole page redirect, reloading the whole Dash app, which is obviously no good. I played around with using the CSS pointer-event attribute to disable the internal `<a>`, however this then disables all the hover events wanted in the first place.

Would it be feasible to add the `href` to the `<a>` produced by `dcc.Link`, modifying its `onclick` to prevent the page being redirected?

**Comment by chriddyp** [comment]
> Would it be feasible to add the href to the <a> produced by dcc.Link, modifying its onclick to prevent the page being redirected?

Yeah, that sounds like the right way to go! It will be _something_  adding an `e.preventDefault()` inside the `a` click handler. I've included a sketch of a solution in here https://github.com/plotly/dash-core-components/pull/130 for someone in the community to run with :slightly_smiling_face:

**Comment by valentijnnieman** [comment]
I am pretty sure this issue has been fixed - I can confirm that the `Link` component spits out an `<a>` including the `href` attribute. Closing this for now!

**Comment by ned2** [comment]
Ah yep, definitely fixed. Thanks for closing. Was super good to see this sorted out.
