### ISSUE TITLE
`dcc.Location` without an `Output` causes the app to fail

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash-core-components#145]
see https://community.plot.ly/t/dash-datatable-issue-rendering-multiple-datatables/7758 and https://community.plot.ly/t/dcc-location-error-loading-dependencies/5083/16

**Comment by mjclawar** [comment]
@chriddyp: Checked to see if this was from a change I made -- I can't replicate this bug locally in v0.17.0 for either of those examples (believe it is no longer a bug in newer versions). This was an error in (at least v0.15).

**Comment by chriddyp** [comment]
Thanks for looking into it! I haven't looked into it myself. I'll post an update on those threads

**Comment by chriddyp** [comment]
Community member confirmed that this isn't an issue anymore. Thanks for triaging @mjclawar !
