### ISSUE TITLE
Markdown (and probably SyntaxHighlighter) default `children` value needs update

### ISSUE THREAD

**Issue by AfroMetal** [plotly/dash-core-components#147]
With dcc 0.15.4 and:

> The children property of dash_core_components.Markdown and dash_core_components.SyntaxHighlighter now accepts an array of strings (previously it had to be a string). Now, if an array is provided, it is collapsed into a string with line breaks (see #134).

now creating `dcc.Markdown()` component without any children value, for an empty component that will be later filled with a callback crashes in React constructor:

```
// must be a string or an array of strings
if(typeof props.children !== 'string') {
    props.children = props.children.join('\n');
}
```
as `children` is not a string, but the default `children` value that crashes on `.join()` call (at least that is what browser console tells me): `TypeError: Cannot read property 'join' of null`.

I think that the default value for `dcc.Markdown.children` should be `""` or empty list.

Or if providing `children` value is required, then Python should catch components without it and raise an exception, as it is it was really hard to find the error.

**Comment by chriddyp** [comment]
Yeah, that `typeof` isn't strict enough, it should just be `if (R.type(props.children) === 'Array')`. I'll fix this one.

**Comment by chriddyp** [comment]
Thanks for reporting!
