### ISSUE TITLE
DatePickerRange initiates callbacks at every selection, before window is closed.

### ISSUE THREAD

**Issue by cherls** [plotly/dash-core-components#152]
Clicking on the dates on the DatePickerRange initiates callbacks at every click. For example, selecting the start date initiates callback, before one can finish selecting the end date. These callbacks have to all finish running and can take a long time if the user clicks around on the DatePickerRange.

**Comment by chriddyp** [comment]
Sounds like we should add a `updatemode` similar to the `Slider` component: `singledate` vs `bothdates` vs `onclose` or something like that.
