### ISSUE TITLE
dcc.Graph shouldn't require an `id`

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash-core-components#167]

**Comment by valentijnnieman** [comment]
@chriddyp I thought this would be as easy as removing the `isRequired` from the `id` prop (and maybe setting a default) but I'm getting this error 
![screen shot 2018-06-28 at 12 08 30](https://user-images.githubusercontent.com/6509622/42028405-7cd63398-7acc-11e8-91fa-de63a1ec036c.png)
when trying to render a `Graph` without an `id`. Setting a default (in `defaultProps`) `id` should just work, shouldn't it?

**Comment by valentijnnieman** [comment]
Fixed in #219
