### ISSUE TITLE
Input 'number' with min and max not checking manual input

### ISSUE THREAD

**Issue by radekwlsk** [plotly/dash-core-components#173]
The `dcc.Input` component set to `type='number'` with `min` and `max` defined checks the value only when using the input's arrows. On manual input any value can be entered, only regexp for `number` is checked.

I think it should apply `min` when entered manually value is lower than allowed and `max` when it is greater than allowed. For example on focus lose or mouse click or even after some delay of not typing.

**Comment by sobayed** [comment]
I agree. When I saw the min/max parameters I assumed that the user inputs would be checked in some way. Allowing any input anyway kind of defeats the purpose (or at least make the forced check configurable).

**Comment by Austin-PAVrus** [comment]
Me too. Trying solve it by making something like:

@app.callback(Output('agentT', 'value'),
[Input('agentT', 'value')],
[State('agentT', 'min'),
State('agentT', 'max')])
def check_agentT_value(val,min,max):
	if val >= min or val<= max:
		raise PreventUpdate
	elif val<min:
		return min
	else:
		return max

leads me to a failure of layout loading with no logs in console...

Is there other ways to check the limits of a manual input? I have 46 numeric fields in my project...

**Comment by valentijnnieman** [comment]
A fix is included in `0.37.0`!
