### ISSUE TITLE
tests are failing

### ISSUE THREAD

**Issue by ned2** [plotly/dash-core-components#176]
I'm struggling to get the tests to run. Possibly I'm just not quite doing it right, as I don't think I've run the DCC tests before now. 

I'm simply invoking `tox`. Which gives this at the end of the test run:

```
======================================================================                         
ERROR: test_gallery (test.test_integration.Tests)                                              
----------------------------------------------------------------------                         
Traceback (most recent call last):             
  File "test/test_integration.py", line 334, in test_gallery                                   
    self.wait_for_element_by_css_selector('#waitfor')                                          
  File "test/test_integration.py", line 47, in wait_for_element_by_css_selector                
    raise e            
NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#waitfor"}
  (Session info: chrome=65.0.3325.181)         
  (Driver info: chromedriver=2.35.528139 (47ead77cb35ad2a9a83248b292151462a66cd881),platform=Linux 4.14.0-041400-generic x86_64)


======================================================================                         
FAIL: test_location_link (test.test_integration.Tests)                                         
----------------------------------------------------------------------                         
Traceback (most recent call last):             
  File "test/test_integration.py", line 420, in test_location_link                             
    self.wait_for_text_to_equal('#test-hash', '#test')                                         
  File "test/test_integration.py", line 58, in wait_for_text_to_equal                          
    raise e            
AssertionError: u'' != '#test'                 

----------------------------------------------------------------------                         
Ran 7 tests in 149.802s                        

FAILED (failures=1, errors=1)
```

**Comment by mjclawar** [comment]
Checks:
- You are using the latest chromedriver (2.3.7 [here](https://chromedriver.storage.googleapis.com/index.html?path=2.37/)) (I was running into issues this morning running tests)
- You updated `dash`, `dash-renderer` and `dash-html-components` to the latest released versions

As a related note, I think the `requirements-dev.txt` should lock the `dash`-related dependencies to avoid this issue.

Here are the more relevant pieces from `pip freeze`: 
```
dash==0.21.0
dash-html-components==0.9.0
dash-renderer==0.11.3
selenium==3.11.0
six==1.11.0
tox==2.9.1
tox-pyenv==1.1.0
```

I ran the tests successfully just now with
```bash
$  python -m unittest discover -s ${HOME}/Projects/oss/dash-core-components -t ${HOME}/Projects/oss/dash-core-components in ${HOME}/Projects/oss/dash-core-components
```

**Comment by ned2** [comment]
Oh, oops. I had forgotten that `bundle.js` isn't version controlled and needs to be generated before running the tests. I'm just making a Python change so didn't bother, which meant I was using a super out of date `bundle.js` from when I generated it some months back. 

I'll close this, but it's possibly also worth pointing out that tox.ini does use a `requirements-locked.txt` by default, but this looks to be fairly old now.

**Comment by chriddyp** [comment]
@ned2 - would you mind creating a `CONTRIBUTING.md` file with a couple of notes about running the tests? It's nice to fill these out while it's still fresh.

**Comment by ned2** [comment]
@chriddyp, sure thing. See #180
