### ISSUE TITLE
Subplots in Dash

### ISSUE THREAD

**Issue by willgdjones** [plotly/dash-core-components#179]
Hello,

I would like to replicate the following subplot behaviour that shares x-axes in Plot.ly, but using Dash instead. Is this possible?

Thank you very much,
https://plot.ly/python/subplots/#subplots-with-shared-xaxes

**Comment by chriddyp** [comment]
It is possible. Everything in plot.ly/python/ can be used in Dash. Just set `dcc.Graph(figure=fig)`

**Comment by willgdjones** [comment]
Hi - yes, I managed to do this actually. Thanks for the reply!
