### ISSUE TITLE
"RangeError: Source is too large" with repeated re-drawing of Scattergl subplots

### ISSUE THREAD

**Issue by slishak** [plotly/dash-core-components#181]
I have a Dash app with a number of Scattergl plots, one of which can have tens of subplots each containing hundreds-thousands of points. After re-drawing the plot containing Scattergl subplots a few times, I get the following error from Plotly.js:

```
plotly-1.35.2.min.js:7 Uncaught RangeError: Source is too large
    at Float64Array.set (<anonymous>)
    at plotly-1.35.2.min.js:7
    at Array.forEach (<anonymous>)
    at Function.b [as update] (plotly-1.35.2.min.js:7)
    at Object.plot (plotly-1.35.2.min.js:7)
    at ha (plotly-1.35.2.min.js:7)
    at Object.ua.plot (plotly-1.35.2.min.js:7)
    at plotly-1.35.2.min.js:7
    at Object.oe.syncOrAsync (plotly-1.35.2.min.js:7)
    at ay.plot (plotly-1.35.2.min.js:7)
```

Not sure if this is an issue for Plotly.js or for here, but seeing as the version of Plotly.js is managed by dash-core-components and that's the package I'm directly using, I'm submitting it here!

**Comment by slishak** [comment]
I'm running on a laptop with Intel integrated graphics and an NVidia GPU, and noticed that Chrome wasn't using the dedicated graphics memory on the NVidia card. I forced Chrome to always use the NVidia GPU and the stability seems to have improved. I will close this issue if I don't see the issue again over the next few days.

**Comment by slishak** [comment]
Switching to the NVidia GPU has not fixed the issue (maybe it has delayed it).

Some other symptoms of the issue are scatter traces are invisible on the plot (although hover data still appears), and sometimes become visible when zooming in. I assumed it was related to running out of GPU memory but it doesn't seem to be the case looking at the memory usage history.

**Comment by chriddyp** [comment]
Can you share a small reproducable example?

**Comment by slishak** [comment]
I think this issue was closely linked to #204 and is no longer occuring.
