### ISSUE TITLE
Graph callbacks not always triggered by Dropdown value or Graph selectedData change events in 0.22.1 - maybe broken by initially returning empty dict

### ISSUE THREAD

**Issue by slishak** [plotly/dash-core-components#188]
I have multiple apps that have Graph `figure` plotting callbacks triggered by multiple inputs, including Dropdown `value` events (both single and multi select) and `selectedData` events from other Graphs. As of version 0.22.1, none of my plots are triggered by these events initially. I can trigger the callbacks using sliders and checkboxes, but the title doesn't change to "Updating..." while the callback is running. Once I've triggered the callback one of these methods, the dropdowns suddenly start working again (although intermittently).

Rolling back to 0.22.0 solves the above problems. I've gone back and forth a few times to double check.

Something that may contribute to this is that when the app first loads, the graph callback is triggered, but there have been no valid user selections to define the plot so I abort the callback by returning an empty dict. If I raise an Exception it seems to work, but I'd prefer not to spit out a traceback to the console in this case. Is raising an Exception the only way to halt termination of a callback without plotting anything?

**Comment by slishak** [comment]
I'm now raising `dash.exceptions.PreventUpdate` to abort callbacks, which avoids the above issue and is more graceful than raising another type of `Exception`. Maybe a mention of `PreventUpdate` could be added to the docs so it's more clear that this is the way to gracefully terminate a callback, instead of returning something?

**Comment by ned2** [comment]
Yep, this definitely should go in the Dash Guide.
