### ISSUE TITLE
triggering page changes with buttons

### ISSUE THREAD

**Issue by dbill23** [plotly/dash-core-components#189]
I've been able to navigate multiple pages using the Multi-Page Apps and URL Support approach documented here...https://dash.plot.ly/urls.

Is there a way to trigger the page change using a button instead of a link like this?
dcc.Link('Navigate to "/page-2"', href='/page-2')

I've been playing around with this for a while but can't figure out how to trigger the same change by clicking a button. Any ideas?

**Comment by mjclawar** [comment]
You should be able to wrap the button with a `dcc.Link` component, like
```python
import dash_html_components as html

dcc.Link(
    html.Button('Navigate to "page-2"'),
    href='/page2')
```

Note that for general help questions like this one, https://community.plot.ly/c/dash is probably your best bet!

Going to close this.

**Comment by dbill23** [comment]
Thanks very much for your quick repsonse. This worked perfectly. Exactly
what I needed.

**Comment by maulberto3** [comment]
Just for the sake of completeness, it works using a button, i.e. from dbc, and its href.
