### ISSUE TITLE
Ability to set a maximum number of intervals?

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash-core-components#222]
As suggested by a community member:

> When I put it this way, the cleanest solution to my problem would be if `dcc.Interval()` supported the idea of counting a certain number of ticks and then stopping by itself, i.e. had something like a `max_intervals` parameter. I’m not sure if you have any other use-cases for that but if so, maybe it’s a feature suggestion?

Full discussion: https://community.plot.ly/t/should-i-use-an-interval-for-a-one-off-delay/11375/6

Seems like a pretty good idea, coul dbe useful for general delays and fits nicely into the existing component API

**Comment by claresloggett** [comment]
Might also be useful to people trying to "turn off" the Interval, e.g. https://community.plot.ly/t/how-to-turn-off-interval-event/5565 ?

That discussion is about turning it off in response to an event, but if there were a `max_intervals` parameter we could presumably turn the timer off manually by setting `max_intervals=n_intervals`.
