### ISSUE TITLE
Ability to supply `figure` without `data`

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash-core-components#223]
v0.22.1 introduced a bug:
```
+            if (intersection(
+                pluck('type', figure.data),
+                ['candlestick', 'ohlc']).length
+            ) {
+                PlotMethod = Plotly.newPlot;
+            } else {
+                PlotMethod = Plotly.react;
+            }
```

now, if `figure.data` is undefined, the `pluck('type', figure.data)` fails. I believe that we should be able to fix this with just a `R.has('data', figure)` check. We should add some tests that supply figure as `None`, `{}`, `{'layout': {}}`, and `{'data': []}`

**Comment by chriddyp** [comment]
Originally reported here: https://community.plot.ly/t/error-loading-layout-after-core-components-0-22-1-and-ngrok/10350/5. We should loop back in that forum post when we get out a fix

**Comment by chriddyp** [comment]
@valentijnnieman - Could you grab this one this week? I've seen a few users report this issue in the forum, seems like it'd be an easy win 😸

**Comment by rmarren1** [comment]
Same as this: https://github.com/plotly/dash-core-components/issues/260
