### ISSUE TITLE
Return a dcc component in a callback returns an error

### ISSUE THREAD

**Issue by valentijnnieman** [plotly/dash-core-components#227]
Hi! Not sure if I'm doing something wrong or if this is a bug, but when I'm trying to return a component from within a callback, I get a (browser) error `Uncaught (in promise) Error: dash_core_components was not found.`

Here's the code I'm using:
```
...
app.layout = html.Div([
  html.Div(id='topbar', children=[
    html.Button(id='add-graph', children='Add Graph')
  ]),
  html.Div(id='output')
])

@app.callback(Output('output', 'children'), 
              [Input('add-graph', 'n_clicks')])
def return_graphs(n_clicks):
  return dcc.Graph(id='graph-{}'.format(n_clicks), figure={'data': {}})
...

```

I've tried other dcc components such as `DatePickerSingle` too, to no avail.

**Comment by T4rk1n** [comment]
Your initial layout doesn't have a dcc component, when it doesn't have a component from a lib, dash does not load the js bundle.

**Comment by valentijnnieman** [comment]
@T4rk1n Ah I see, thanks! Perhaps we can improve that at some point.

**Comment by Daboudette** [comment]
Hi :) How did you finally fix the issue ? With  html.Div(id='output,children'=[]) ??
