### ISSUE TITLE
Use of git tags

### ISSUE THREAD

**Issue by moorepants** [plotly/dash-core-components#233]
Hi, I package dash for conda and it would be very helpful if git tags were used to tag releases. It is difficult to match which pypi release corresponds with which changes in the codebase without them.

**Comment by chriddyp** [comment]
Makes sense. I've been doing this lately:
![image](https://user-images.githubusercontent.com/1280389/42637659-c19ee7de-85b9-11e8-976b-2f93d8f3513f.png)

But I'll add to some type of official release docs. FYI @plotly/dash , I usually do this with e.g.
```
git tag -a 'v0.22.1' -m 'v0.22.1'
```
and I do the tag right after I run `npm run publish-all`

**Comment by moorepants** [comment]
Yes, those would be helpful on all the dash related repos. It mostly seems that recent releases haven't had tags pushed up.

**Comment by valentijnnieman** [comment]
Closing this because we've lately been pushing git tags - the `publish` script also includes a step that pushes up git tags automatically - DCC developers should be using that to publish after merging.
