### ISSUE TITLE
Uploader Raises 3x Callbacks per item dropped

### ISSUE THREAD

**Issue by adithyaj** [plotly/dash-core-components#245]
I noticed in my tests that the Upload component raises 3 callbacks every time for every file I upload. When uploading files with a lot of contents this tends to take a while too.

**Comment by T4rk1n** [comment]
You probably have 3 inputs on the callback, keep the one with data as input and get the rest as state.

Example:
```
@app.callback(Output('output', 'children'),
                  [Input('upload-data', 'contents')],
                  [State('upload-data', 'filename')])
def on_upload(contents, filename):
    ...
```
