### ISSUE TITLE
Pass `figure` through `go.Figure` for validation?

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash-core-components#257]
If a user supplies their data with dictionaries and lists, they won't get validation. Perhaps we should pass the figure through `plotly.graph_objs.Figure` to give them validation.

This will require us to write some intermediate code between the auto-generated code and the serialization, which we haven't done before. It might be a good use case to try out these types of abstractions.

**Comment by rmarren1** [comment]
Will happen in plotly/dash#340

**Comment by rmarren1** [comment]
^ Looks like this  is an issue in plotly.py
https://github.com/plotly/plotly.py/issues/1289

**Comment by frogger72** [comment]
Is figure validation already implemented? I am looking for ways to boost performance and would prefer to turn this off if it's on by default.

**Comment by alexcjohnson** [comment]
No, if you construct your `figure` as a plain `dict` it will not be validated. @chriddyp my gut reaction is we should leave it that way, if people do want validation (with its associated overhead) they have plenty of options to get that already. Feel free to reopen though if you disagree.
