### ISSUE TITLE
Varying number of graphs but still access each of their component properties?

### ISSUE THREAD

**Issue by kimrants** [plotly/dash-core-components#258]
Dear, 

Do you have code or suggestions to solve the following?

I have a Dashboard that displays either 1, 2 or 3 scatterplots based on some user input.

Thus, I currently have html.Div(id='output') , where the scatters are supposed to be plotted and then I have a function that returns a div-tag with either 1,2 or 3 graphs.

However, later, I want to use the ‘clickData’ property of the graphs, but I don’t know how to access them through the ‘output’ id? Is there a way to do this?

Thank you!

**Comment by chriddyp** [comment]
> However, later, I want to use the ‘clickData’ property of the graphs, but I don’t know how to access them through the ‘output’ id? Is there a way to do this?

You should be able to access them through the underlying IDs of the underlying graph components

**Comment by kimrants** [comment]
I cannot. I get this error:
"Attempting to assign a callback to the
component with the id "graph" but no
components with id "graph" exist in the
app's layout."

I guess this is because the graph has not been created yet at that point.

Do you know a work-around?
Would help me tremendously

2018-08-07 21:35 GMT+01:00 Chris Parmer <notifications@github.com>:

**Comment by chriddyp** [comment]
> "Attempting to assign a callback to the component with the id "graph" but no components with id "graph" exist in the app's layout."

Right, but the rest of the error message tells you how to get around this by setting the config variable `app.config['suppress_callback_exceptions']=True`.

**Comment by kimrants** [comment]
Thank you so much!! I’m sorry I missed this, but thank you!
