### ISSUE TITLE
metadata.json

### ISSUE THREAD

**Issue by khizarCode** [plotly/dash-core-components#31]
MANIFEST.in shows the following
>>include dash_core_components/metadata.json

https://github.com/plotly/dash-core-components/tree/master/dash_core_components
does not include metadata.json

As a result, I see the following upon trying to run dash-stock-tickers-demo-app

```
Traceback (most recent call last):
  File "app.py", line 2, in <module>
    import dash_core_components as dcc
  File "c:\users\kqureshi\downloads\dash-core-components\
init__.py", line 10, in <module>
    'dash_core_components'
  File "C:\Python27\lib\site-packages\dash\development\co
e 22, in load_components
    with open(metadata_path) as data_file:
IOError: [Errno 2] No such file or directory: 'c:\\users\
ash-core-components\\dash_core_components\\metadata.json'
```

Thanks in advance. Hope I'm not missing something here

**Comment by khizarCode** [comment]
Checked C:\Python27\lib\site-packages\dash\development\component_loader.py

Saw the following
    # Start processing
    with open(metadata_path) as data_file:
        json_string = data_file.read()
        data = json\
            .JSONDecoder(object_pairs_hook=collections.OrderedDict)\
            .decode(json_string)

**Comment by chriddyp** [comment]
> https://github.com/plotly/dash-core-components/tree/master/dash_core_components
does not include metadata.json

This file was actually just in the `.gitignore`, so it wasn't committed to the repo.

I noticed that `dash-core-components` was in your `downloads` folder. That won't actually work - you need to install the package through the python package manager `pip`. Could you try following the instructions in the user guide here? https://plot.ly/dash/installation? 

I'll close this for now but feel free to reopen it if the instructions in the user guide don't work for you.
