### ISSUE TITLE
Autorange values stored in dcc.Graph.figure['layout']['xaxis' 'yaxis']['range'] no longer available after version v0.30.1

### ISSUE THREAD

**Issue by crosenth** [plotly/dash-core-components#321]
I was using the initial autorange values to "hold" my plotly.graph_objs.Layout plot axes from recalculating when dynamically adding or removing plotly.graph_objs.scatter.Markers.  Three questions:

1. Is there some place else I can read Layout axes range values after they have been calculated by the autorange function?
2. Is there a better way to "hold" a plotly.graph_objs.Layout to the initial autorange values?
3. Can the plotly.graph_objs.Layout axes autorange function be invoked directly?

**Comment by bcliang** [comment]
This looks fixed with https://github.com/plotly/plotly.js/pull/3236

Solution is to define the layout property uirevision (yaxis.uirevision)

In my case (time-series data), I will hold the figure layout (layout.uirevision) and update xaxis.uirevision with new range.

**Comment by crosenth** [comment]
Hi bcliang,

Thanks for pointing our the new feature.  I made a comment in the forums that the View still resets unless I necessarily interact with the Figure (Zoom in, out, autoscale, etc) which is not ideal.  I would like to preserve the IU state without doing that.  You can use cchridyp's example here to see what I mean https://community.plot.ly/t/preserving-ui-state-like-zoom-in-dcc-graph-with-uirevision/15793.

**Comment by crosenth** [comment]
Mysteriously fixed as of dash==1.8.0, thank you Dash team
