### ISSUE TITLE
disabled prop for dcc.Interval is not used.

### ISSUE THREAD

**Issue by T4rk1n** [plotly/dash-core-components#325]
We have a `disabled` prop in the prop type definition of the Interval component, but it is not actually used by the code to disable the interval. Either remove it as we have the max_intervals=0 logic to stop the interval or make it stop the interval.

https://community.plot.ly/t/interval-component-cannot-be-disabled-via-callback/14455

Proposed solution:
- [ ] replace the props argument in setInterval by `this.props`.
- [ ] remove the disabled check from the interval.
- [ ] check for disabled prop in `componentWillReceiveProps`.stop the loop if false .
- [ ] restart the loop on disabled = True in componentWillReceiveProps if it was stopped.

**Comment by T4rk1n** [comment]
Actually, we check for disabled only while doing setProps in the interval, but it takes the props from arguments and not `this` so it isn't updated. It's also the wrong place for that check as the loop will still run after setting disabled.

The disabled props should actually be checked in `componentWillReceiveProps` and stop the loop if false.

**Comment by shammamah** [comment]
@T4rk1n By "stop the loop", do you mean that `window.clearInterval` should be called? Or is there some other behaviour that should occur?

**Comment by T4rk1n** [comment]
Yes that is what I meant.

**Comment by philip-peterson** [comment]
This issue is addressed by https://github.com/plotly/dash-core-components/pull/436

**Comment by alexcjohnson** [comment]
Closed by #436 - thanks @philip-peterson 🎉
