### ISSUE TITLE
Tabs uses old PropTypes syntax

### ISSUE THREAD

**Issue by rmarren1** [plotly/dash-core-components#335]
These lines would break in React 16, can we just use the normal `PropTypes` way?
https://github.com/plotly/dash-core-components/blob/b4ddfa592d4f4b6ff7056dbf25f43d5cc2c47c9a/src/components/Tabs.react.js#L377-L379

@valentijnnieman

**Comment by valentijnnieman** [comment]
Which is what exactly? I see the same syntax on all other components, what am I missing?

**Comment by rmarren1** [comment]
Okay great, I was wondering if there was a functional difference between the two here since plain `PropTypes` was used for the other `Tabs` props. I'll just edit those

**Comment by valentijnnieman** [comment]
I don't think so, it was something I copied over from somewhere, but you're right in that we should use the `prop-types` package for React 16 support! Thanks for making a PR :)

**Comment by rmarren1** [comment]
https://github.com/plotly/dash-core-components/pull/338
