### ISSUE TITLE
Issue with a Tabs test case

### ISSUE THREAD

**Issue by rmarren1** [plotly/dash-core-components#336]
https://github.com/plotly/dash-core-components/blob/b4ddfa592d4f4b6ff7056dbf25f43d5cc2c47c9a/test/test_integration.py#L580-L586

This portion of the test is not executing consistently. There is a moment where the state of the `#tabs-content` is `''` and is present on the screen before the initial callback is fired, so sometimes `''` is compared with `'Default selected Tab content 1'` and throws an error. I got this to work temporarily by putting `time.sleep(1)` after `self.startServer(app=app)`

**Comment by rmarren1** [comment]
@valentijnnieman

**Comment by T4rk1n** [comment]
It should use the WebDriverWait api for the text, I can patch up the wait_for_text_to_equal with the one I made in dash-auth not long ago.

**Comment by valentijnnieman** [comment]
@T4rk1n That would be great, thanks!
