### ISSUE TITLE
Upload component not loading xlsx but works fine with csv on remote server but works fine locally

### ISSUE THREAD

**Issue by davidpham87** [plotly/dash-core-components#345]
Hello,

I have the following problem: my upload components reads csv and xlsx when I use dash locally through `python app.py`. 

However, when I deploy the app, the upload components does not read the content of the xlsx and the callback receives a `None` argument for contents.  The server runs _gunicorn_ with _nginx_ on centos 7 with a personal ssl certificate created with _openssl_. To be clear, uploading csv works (in the example below the filename would be displayed) whereas uploading a csv would print "No contents".

The xlsx are fairly small around 5mb.

Thanks for your help!

```{python}
import dash_core_components as dcc
import dash_html_components as html

app = dash.Dash()
app.css.config.serve_locally = True
app.scripts.config.serve_locally = True

app.layout = html.Div([
    dcc.Upload(
        id='upload-data',
        children=html.Div([
            'Drag and Drop or ',
            html.A('Select Files')
        ]),
        style={
            'width': '100%',
            'height': '60px',
            'lineHeight': '60px',
            'borderWidth': '1px',
            'borderStyle': 'dashed',
            'borderRadius': '5px',
            'textAlign': 'center',
            'margin': '10px'
        },
        max_size=-1,
        # Allow multiple files to be uploaded
        multiple=False
    ),
    html.Div(id='output-data-upload'),
])

@app.callback(dash.dependencies.Output('output-data-upload', 'children'),
             [dash.dependencies.Input('upload-data', 'contents'),
              dash.dependencies.Input('upload-data', 'filename')])
def update_output(contents, filename):
    if contents is not None:
        # do something with contents
        children='processed data from file ' + filename
        return children
    else:
        return 'no contents'

if __name__ == '__main__':
    app.run_server(debug=True)
```

**Comment by ned2** [comment]
How big are your CSVs? According to nginx docs the default for the relevant
param (client_max_body_size) is 1M. So if your CSVs are less than this,
then that's likely what's going on. Just up the max value.


http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size

**Comment by davidpham87** [comment]
Thanks a lot @ned2! This solved my issue!
