### ISSUE TITLE
upgrade to plotly.js 1.42.0

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash-core-components#351]
https://github.com/plotly/plotly.js/releases/tag/v1.42.0

**Comment by T4rk1n** [comment]
I'll do it this time, while working on plotly/dash#422 I found out that our local copy of plotly.js is not the same as the one hosted externally.

```
Failed to find a valid digest in the 'integrity' attribute for resource 'https://cdn.plot.ly/plotly-1.39.1.min.js' with computed SHA-256 integrity 'JrzbYvyiKhG74PbwoEFOLeAMgW/U02Did6YDkzSsJhE='. The resource has been blocked.
```

I generate the hash from the local file, it should be the same.

Same for:
- https://unpkg.com/react-virtualized@9.9.0/styles.css
- https://unpkg.com/react-virtualized-select@3.1.0/styles.css
- https://unpkg.com/rc-slider@6.1.2/assets/index.css

**Comment by chriddyp** [comment]
`1.42.1` now: https://github.com/plotly/plotly.js/releases/tag/v1.42.1
