### ISSUE TITLE
code editor widget via react-codemirror 

### ISSUE THREAD

**Issue by sdementen** [plotly/dash-core-components#365]
I see in https://github.com/plotly/dash-core-components/blob/master/package-lock.json references to `codemirror` and `react-codemirror`.
Is there some "code editor" widget leveraging this component ? 
Or would codemirror just be used for the `SyntaxHighlighter` ?

**Comment by valentijnnieman** [comment]
Hi @sdementen, yes I believe that's used for the SyntaxHighligher component, no code editor component yet, unfortunately!
