### ISSUE TITLE
Update react-dates package to its latest

### ISSUE THREAD

**Issue by valentijnnieman** [plotly/dash-core-components#398]
`react-dates` is on 18.2.2 - dash-core-components is using version 12.3.0. This will be a breaking change for Dash users.

To get this over the finish line, we will have to update our DatePicker components with the changes in the API made by `react-dates`. I think we should also go ahead and add unit tests and (more) integration tests, so that we are aware of what breaks/changes and have a more stable platform for the future.

**Comment by wbrgss** [comment]
@Marc-Andre-Rivet can this be closed via #508 ?

**Comment by byronz** [comment]
should bump version to V20.2.5 in #600
