### ISSUE TITLE
Plotly.js updates changelog are not pointing to the plotly.js repo

### ISSUE THREAD

**Issue by T4rk1n** [plotly/dash-core-components#425]

**Comment by alexcjohnson** [comment]
From my comment in #423:
> importing the whole plotly.js changelog en masse means that all of these links (ie links like `#3360` to plotly.js PRs/issues) are broken, and ideally would need to be prefixed with `plotly/plotly.js`

I'm assuming this has been discussed somewhere before, but is it really important to duplicate the entire plotly.js changelog? Could we just summarize it instead and link to the original, something like:

- Updated plotly.js to version 1.43.1, including feature release [1.43.0](https://github.com/plotly/plotly.js/releases/tag/v1.43.0) and patch releases [1.43.1](https://github.com/plotly/plotly.js/releases/tag/v1.43.1), [1.42.5](https://github.com/plotly/plotly.js/releases/tag/v1.42.5), [1.42.4](https://github.com/plotly/plotly.js/releases/tag/v1.42.4), and [1.42.3](https://github.com/plotly/plotly.js/releases/tag/v1.42.3). These releases contain the `multicategory` axis type, the `uirevision` feature, the `hovertemplate` attribute, alignment options for titles and legend items, and numerous other features and bug fixes.

**Comment by T4rk1n** [comment]
I think we should define a procedure for updating plotly.js and document it somewhere.

Something along the lines of:

- Download the latest plotly.js from the cdn
`$ wget https://cdn.plot.ly/plotly-1.43.1.min.js`
- Update `dash_core_components/__init__.py` plotly.js `external_url`
- Update `MANIFEST.in`
- Update `CHANGELOG.md` with links to the releases and a description of the changes.

**Comment by bpostlethwaite** [comment]
@alexcjohnson can you please define and document this policy and modify the respective CHANGLELOG accordingly. I really don't think we need discussion here, @alexcjohnson can make the new policy increasing team velocity and we can move on to more exciting challenges :)
