### ISSUE TITLE
remove dash-table-experiments from tests

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/dash-core-components#428]
dcc uses `dash_table_experiments` in its tests - can we just move these tests into `dash_table` and 🔪 from this repo?

https://github.com/plotly/dash-core-components/blob/aa2ff089a3f21cd333eee47eadbf25bdfcf9de42/dev-requirements.txt#L6

https://github.com/plotly/dash-core-components/blob/aa2ff089a3f21cd333eee47eadbf25bdfcf9de42/test/test_integration.py#L17

cc @Marc-Andre-Rivet

**Comment by bpostlethwaite** [comment]
Yes we can do this. `dash_table_experiments` is deprecated/frozen and it is ok if it no longer works with later versions of `dash` and `dash-renderer`.
