### ISSUE TITLE
html.A("display nested html file", href="/fubar/text.html") only redisplays the app

### ISSUE THREAD

**Issue by paul-shannon** [plotly/dash-core-components#429]
````html.A```` works fine when href is any url external to my app.  But when the href is to an html file nested below - in a subdirectory of - my app's location, then clicking the html.A link only serves to reload the app.  I must be missing something obvious, something simple.

Here's the code.    Any suggestions?   
Also: is there a parameter to html.A which emulates ````target="_blank"```` so that the new content is displayed in a new browser page, allowing the dash app to continue, unaffected?

Thank you!

````
import dash
from dash.dependencies import Input, Output, State
import dash_core_components as dcc
import dash_html_components as html

external_stylesheets = ['https://codepen.io/chriddyp/pen/bWLwgP.css']
app = dash.Dash(__name__, external_stylesheets=external_stylesheets)

app.scripts.config.serve_locally = True

app.layout = html.Div([
    html.A('Navigate to google.com', href='http://google.com'),
    html.Br(),
    html.A('Navigate to nested web page', href='/fubar/test.html'),
])

if __name__ == "__main__":
    app.run_server(host='0.0.0.0', port=8051)
````

**Comment by Marc-Andre-Rivet** [comment]
@paul-shannon 

> Also: is there a parameter to html.A which emulates target="_blank"
No need to emulate. Just add `target='_blank'` to your html.A component and it should work.

> when the href is to an html file nested below [...] then clicking the html.A link only serves to reload the app
This is happening because the nested HTML file is an unknown asset of your app. Dash redirects you to the top-level URL when it hits an unknown resource. You can do something like here to expose your nested file https://community.plot.ly/t/how-can-i-use-my-html-file-in-dash/7740 or the equivalent below:

```
import dash
from dash.dependencies import Input, Output, State
import dash_core_components as dcc
import dash_html_components as html

# Added
import flask
import os
from flask import Flask

# Added
server = Flask(__name__)
STATIC_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'static')

external_stylesheets = ['https://codepen.io/chriddyp/pen/bWLwgP.css']
app = dash.Dash(__name__, external_stylesheets=external_stylesheets, server=server)

app.scripts.config.serve_locally = True

app.layout = html.Div([
    html.A('Navigate to google.com', href='http://google.com', target='_blank'),
    html.Br(),
    html.A('Navigate to nested web page', href='/fubar/test.html'),
])

# Added
@app.server.route('/fubar/<resource>')
def serve_static(resource):
    return flask.send_from_directory(STATIC_PATH, resource)

if __name__ == "__main__":
    app.run_server(host='0.0.0.0', port=8051)
```

**Comment by Marc-Andre-Rivet** [comment]
Closing as answered. Do consider using the community forum (https://community.plot.ly/) in the future for questions as it offers greater visibility and also gives you access to insight from members of the community :)
