### ISSUE TITLE
Not able to resize dropdowns

### ISSUE THREAD

**Issue by mbkupfer** [plotly/dash-core-components#431]
I can't get my dropdown to be a different height. I even saw this thread on the plotly community which showed it was possible: https://community.plot.ly/t/dcc-dropdown-change-height/17464, but I couldn't manage to change a dropdowns height when I tried it. 

Even with this simple app it doesn't work:
```
import dash
import dash_html_components as html
import dash_core_components as dcc

app = dash.Dash()

app.layout = html.Div(
    dcc.Dropdown(
        id='dropdown',
        value='foo',
        options=[
            {'label': 'foo', 'value': 'foo'},
            {'label': 'bar', 'value': 'bar'}
        ],
        style={'height': '5px'}
    )
)

app.run_server(debug=True)

```
Based on my inspector tool, it looks like the style is resizing (the shaded blue area), but the element is still overflowing. 

![image](https://user-images.githubusercontent.com/6313008/50660185-c5fe7280-0f53-11e9-84ea-aa71e9b352d7.png)

## Installed versions

```
>>> import dash
>>> import dash_core_components as dcc
>>> dash.__version__
'0.35.0'
>>> dcc.__version__
'0.38.0'

```

**Comment by mbkupfer** [comment]
This was fixed by making the dropdowns inline elements. 

For those curious, below is the solution to the above code:

```
import dash
import dash_html_components as html
import dash_core_components as dcc

app = dash.Dash()

app.layout = html.Div(
    dcc.Dropdown(
        id='dropdown',
        options=[
            {'label': 'foo', 'value': 'foo'},
            {'label': 'bar', 'value': 'bar'}
        ],
        style={'height': '5px',  'display': 'inline-block'}
    )
)

app.run_server(debug=True)

```

**Comment by asiago-pressato** [comment]
This solution makes the dropdown arrow disappear
