### ISSUE TITLE
Remove Event system

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/dash-core-components#433]
Companion issue to https://github.com/plotly/dash/issues/531

Events are used only lightly in this repo. The changes I see to remove them completely:

- `Graph` has events, and corresponding properties with the data, for things like click events, hover events... I don't see any need to use the events instead of just letting the property trigger the callback, but folks using the events would need to alter their code. Do we need to add timestamps for these, or is the existence of the data properties enough?

- A bunch of components expose `change` events, fired with every character typed for example. The underlying value will also trigger a callback, I believe in all of these cases, so I don't think we're losing any functionality, but we may want to add timestamps - to *all* core components in fact - to help distinguish most-recent-user-input, for cases of multiple parallel ways to update the same output, as described in https://github.com/plotly/dash/issues/531

- `Input` already has `n_blur[_timestamp]` and `n_submit[_timestamp]` with no corresponding events. It doesn't even have a `change` event, but the note above ^^ still may apply to it.

- `Interval` currently fires an event *and* increments `n_interval` - so we simply need to remove the event. No timestamp property is provided, would be an easy add if anyone was interested.

- `Textarea` currently exposes `blur` and `click` events, which need to be updated to properties.

**Comment by Marc-Andre-Rivet** [comment]
Seems like the only places we’re a bit fuzzy on the impact is dcc.Graph and some other dcc components that use the `change` event and that we may want to check behavior w/ props — talked a bit with Nicolas about the Plotly.js React wrapper before the holidays and there was mention of the graph modifying certain value that React would have considered immutable, wondering if we will run into issues where the event is the only way, as-is, to get the trigger correctly / consistently?

**Comment by Marc-Andre-Rivet** [comment]
All good by me.
