### ISSUE TITLE
Feature request: Add a button component

### ISSUE THREAD

**Issue by yuvval** [plotly/dash-core-components#45]
Hi,

Could you please add a regular GUI button component to dash-core-components?

Is there any workaround that is available for the meanwhile?

Thanks for the great work in this project.

**Comment by chriddyp** [comment]
There is a new `n_clicks` property that is available on every `dash_html_components` element. This property increments by 1 every time it is clicked on. So, you can use a button like this:
```
layout = html.Div([
    html.Button(id='my-button', n_clicks=0),
    html.Div(id='my-output')
])

@app.callback(Output('my-output', 'children'), [Input('my-button', 'n_clicks')])
def display_number_of_clicks(n_clicks):
   return 'You have clicked on the button {} times'.format(n_clicks)
```

**Comment by yuvval** [comment]
Great
Thanks a lot!
