### ISSUE TITLE
validation of dcc.Input with type="number" makes entering negative numbers difficult

### ISSUE THREAD

**Issue by ned2** [plotly/dash-core-components#455]
When a `dcc.Input` component has `type="number"`, it's difficult to get the field to accept negative numbers due to the client-side validation. A `-` character is not permitted unless it precedes a number, which means you have to to enter the digits of your desired number first, before moving the cursor to the start of the field and entering the `-` character.

When the last character in the field is deleted the field's contents are also immediately set to `0`, which I find incurs some amount of cognitive friction when editing the field's contents. I'm guessing both these properties of the validation are intended to always ensure the current value of the field is a valid number, however this comes at the cost of usability I think. I also wonder how important this invariant is to maintain given that an invalid (ie non-numeric) value can be set as an initial value in the layout and therefore can be sent through to the callback.

**Comment by Marc-Andre-Rivet** [comment]
@ned2 Thanks for pointing this issue out. Agree that usability is taking a toll here and needs to be improved -- something as simple as behaving like a normal ```<input type='number' />``` would be better.

**Comment by Marc-Andre-Rivet** [comment]
Discussion about the feature's details in the PR, starting around:
https://github.com/plotly/dash-core-components/pull/580#pullrequestreview-260869321
