### ISSUE TITLE
issue with `dcc.Store('local')` ?

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash-core-components#456]
I haven't investigated this, but the community report looks valid: https://community.plot.ly/t/dcc-store-local-cause-error-loading-dependencies-but-not-dcc-store-memory/19056

**Comment by bcliang** [comment]
I can't seem to replicate the error in testing. However, I have a branch with a hotfix here: https://github.com/bcliang/dash-core-components/commit/92374676c87d18930f03190ca2e6b6d2ca18fc38
