### ISSUE TITLE
Add n_intervals_timestamp to Interval component

### ISSUE THREAD

**Issue by slishak** [plotly/dash-core-components#465]
If I have a callback that depends on a button and an interval, it is very difficult to tell whether the callback was triggered by the button being clicked or the interval being triggered. With multiple buttons, you can use `n_clicks_timestamp` to find which was most recently clicked. However, at the moment comparing whether an interval was triggered more recently than a button click is pretty messy. Is it possible to add in that property?

**Comment by alexcjohnson** [comment]
We have a better solution to this - which has already been merged and will be in the next release: callback context, that directly tells you which input(s) triggered the call https://github.com/plotly/dash/pull/608

I'm not quite ready to say we'll deprecate all the `_timestamp` props, but I don't think we want to add any more until we see if there are cases the callback context doesn't cover.

**Comment by slishak** [comment]
Agreed, that looks like a much cleaner solution! Looking forward to deleting the workarounds in all my apps when that comes out :)

**Comment by alexcjohnson** [comment]
dash 0.38 is out with `dash.callback_context` (note the name - it's still called `dash.callback` in the changelog). We'll collect discussions about the future of `*_timestamp` properties in https://github.com/plotly/dash-core-components/issues/467
