### ISSUE TITLE
Vertical Slider has stopped working

### ISSUE THREAD

**Issue by pfbuxton** [plotly/dash-core-components#479]
Hello,
Vertical Sliders have stopped working (I think this happened in the most recent update, but am not certain)
However, vertical RangeSlider's still work in vertical mode.
Thanks,
Peter

```python
import dash
import dash_core_components as dcc
import dash_html_components as html

app = dash.Dash(__name__)


app.layout = html.Div(children=[
    html.H1(children='Vertical Slider has stopped working.'),
    html.Div([
        dcc.Slider(
            id='mhd_window_slider',
            min=0.05,
            max=1.4,
            step=0.005,
            value=0.5,
            vertical=True,
        )
    ], style={ 'width':'50px', 'height':'500px' }),
    
    html.H1(children='Vertical RangeSlider still works.'),
    html.Div([
        dcc.RangeSlider(
            id='mhd_clim_slider',
            count=1,
            min=0,
            max=3,
            step=0.01,
            value=[0.02, 1],
            vertical=True,
        )
    ], style={ 'width':'50px', 'height':'500px' }),
])

if __name__ == '__main__':
    app.run_server(debug=True)
```

**Comment by Marc-Andre-Rivet** [comment]
@pfbuxton Investigating

**Comment by happyshows** [comment]
Same here.

![image](https://user-images.githubusercontent.com/3208181/53964913-d6e37580-40b5-11e9-98dc-d0dc2c0c27a6.png)

![image](https://user-images.githubusercontent.com/3208181/53964948-ebc00900-40b5-11e9-89c9-497e0d678127.png)

**Comment by happyshows** [comment]
I think adding "min-height" to the css class of `.rc-slider-vertical` will fix it, but obviously it's not the long term solution.

**Comment by Marc-Andre-Rivet** [comment]
This regression was introduced with the loading components work. The additional wrapper div is causing the issue: https://github.com/plotly/dash-core-components/blame/master/src/components/Slider.react.js#L24

The additional div is not present for the Range Slider https://github.com/plotly/dash-core-components/blob/master/src/components/RangeSlider.react.js#L25 hence the difference in behavior.

The wrapper is required to the loading component functionality to work as the `data-*` props to get passed down the the actual Slider -- which is not a problem for the underlying RangeSlider.

Expected resolution is:
- vertical slider works as expected
- loading state works correctly with slider
- minimally add a visual test for vertical slider

As a temporary fix, the wrapper can have `display: initial;` applied to it and it.

The probable fix on our side is also probably to apply `style={{display: 'initial'}}` unto the wrapper div.

**Comment by heartsmith** [comment]
Hi, I tried using the `style={{display: 'initial'}} ` on my code like below:

```
html.Div(
	dcc.Slider(
		id='slider-terminal5r',
		min=0,
		max=3,
		value=3,
		step=1,
		marks={
			0: {'label': 'OFF', 'style': {'color': '#f50'}},
			1: {'label': 'Bot.'},
			2: {'label': 'Mid.'},
			3: {'label': 'Top', 'style': {'color': '#77b0b1'}}
		},
		updatemode='drag',
		vertical='True'
	),className = 'one column', style={'height': '200px', 'display': 'initial'}
),
```

However, the result is still the same. Did I use it wrong? I need to demonstrate my interface next week, but I just realized that I had this problem after updating my library.
Any thought? Thank you.

**Comment by alexcjohnson** [comment]
@heartsmith I believe you want a boolean `vertical=True`, not a string `vertical='True'`

**Comment by heartsmith** [comment]
@alexcjohnson Hi Alex. Thank you for your help. :) I tried using your fix, but the result is still the same like below. 

![image](https://user-images.githubusercontent.com/32376497/59181036-880e1600-8ba5-11e9-8f97-70323e5e7952.png)
