### ISSUE TITLE
Feature request: Log scaling on sliders

### ISSUE THREAD

**Issue by the-rccg** [plotly/dash-core-components#484]
Would be great to have logarithmic ranges available for slider and rangeslider. 

Similar features are available for the graphing axis and have already implemented in the React components for dash-daq (e.g. the tank at https://github.com/plotly/dash-daq/blob/master/src/components/Tank.react.js) which might make adding the feature easier.

Question has been asked about it and the answer make it unnecessary complicated by adding an intermediary function (you select 10, 100, 1000 which gets processed as 1,2,3 and then again adjusted to 10, 100, 1000), rather than adjusting it visually. https://community.plot.ly/t/is-it-possible-to-have-rangeslider-with-geometric-step-increase/5451/5

I do not understand enough about React at this point to figure out how to implement it, maybe someone else has interest in it, otherwise I'll make a pull request once I figure out how React works and get it implemented.

**Comment by Marc-Andre-Rivet** [comment]
@the-rccg Thanks for the comment. We are using https://www.npmjs.com/package/rc-slider under the hood and it does not support that functionality (https://github.com/react-component/slider/issues/393). At the moment, the best option, even-though it's more complex,  is to use an intermediary function to generate the value.

**Comment by the-rccg** [comment]
Makes sense. Thank you very much for your reply!
