### ISSUE TITLE
Switch to 0.39 breaks Slider

### ISSUE THREAD

**Issue by klnrdknt** [plotly/dash-core-components#485]
Concerning this issue:
https://community.plot.ly/t/bug-slider-render-classname-on-wrong-element/20536

> As of a recent update I think, the className property is output to a different html on the Slider, resulting in the slider collapsing, while e.g. the RangeSlider renders completely fine.

> RangeSlider “col-10” is in the right place
> ![image](https://user-images.githubusercontent.com/35272820/54121793-a2e0bb00-43fb-11e9-9318-16ccf9d1b1bd.png)

> Slider (surrounding div has no “col-10” as it is supposed to)
> ![79dcf046202dd47a83de187814f3470d3587a9e4](https://user-images.githubusercontent.com/35272820/54121802-ad02b980-43fb-11e9-9ed8-b96f951033e7.png)

It still happens. I can fix it simply by switching from 0.39 back to 0.38. Any hidden changes in the versioning 

It looks like this:
![image](https://user-images.githubusercontent.com/35272820/54121554-10d8b280-43fb-11e9-820d-baf61e769309.png)
But should look like this:
![image](https://user-images.githubusercontent.com/35272820/54121638-4aa9b900-43fb-11e9-9979-9ecad3fd694c.png)

**Comment by Marc-Andre-Rivet** [comment]
@klnrdknt Could you provide the relevant styles used in the example above. Thanks.

**Comment by klnrdknt** [comment]
Apart from bootstrap, the only stuff affecting the Slider should be:

```.rc-slider-rail {

    position: absolute;
    width: 100%;
    background-color: #e9e9e9;
    height: 4px;

}

.rc-slider {

    position: relative;
    height: 14px;
    padding: 5px 0;
    width: 100%;
    border-radius: 6px;
    box-sizing: border-box;
    -webkit-tap-highlight-color: rgba(0, 0, 0, 0);

}

.rc-slider-track {

    position: absolute;
    left: 0;
    height: 4px;
    border-radius: 6px;
    background-color: #007bff;

}

.rc-slider-dot {

    position: absolute;
    bottom: -2px;
    margin-left: -4px;
    width: 8px;
    height: 8px;
    border: 2px solid #e9e9e9;
    background-color: #e9e9e9;
    cursor: pointer;
    border-radius: 50%;
    vertical-align: middle;

}

.rc-slider-handle:hover {
  background-color: #007bff;
  border: solid 2px #007bff;
}

.rc-slider-handle {

    position: absolute;
    margin-left: -7px;
    margin-top: -5px;
    width: 18px;
    height: 18px;
    cursor: pointer;
    border-radius: 50%;
    border: solid 2px #428bca;
    background-color: #428bca;

}

.rc-slider-mark {

    position: absolute;
    top: 18px;
    left: 0;
    width: 100%;
    font-size: 12px;

}

.rc-slider-mark-text {

    position: absolute;
    display: inline-block;
    vertical-align: middle;
    text-align: center;
    cursor: pointer;
    color: #999;

}

.rc-slider-with-marks {
  margin-bottom: 1.5rem;
}

```

Did the css change inbetween versions?
