### ISSUE TITLE
DatePickerSingle doesn't invoke callback when date is cleared

### ISSUE THREAD

**Issue by derekclee** [plotly/dash-core-components#510]
The `DatePickerSingle` component doesn't invoke the `setProps` callback when a date is cleared.  Instead, internal state is set but the consuming app is not informed.

I have a fix (with tests) and would like to create a PR but I don't see to have the ability to push up a branch.

**Comment by alexcjohnson** [comment]
Thanks @derekclee! We'd welcome a PR, can you just push to your own fork and PR from there?

**Comment by derekclee** [comment]
Will do!

**Comment by derekclee** [comment]
PR: https://github.com/plotly/dash-core-components/pull/511

**Comment by alexcjohnson** [comment]
Closed by #511
