### ISSUE TITLE
Feature Request: Add support for drill down to "dcc.graph"

### ISSUE THREAD

**Issue by matthewchan15** [plotly/dash-core-components#512]
Currently the methodology to produce a graph that is able to "drill down" can be difficult to produce. I talked to  @chriddyp and we discussed adding another piece of metadata to the `clickData` that the user can use to help create their logic.

The main issue with drill downs is being able to know what graph you're currently on.  By knowing what graph you are currently on, you can create the logic to determine what data/graphs to render and filter. Since there are n + 1 graphs it's hard to determine which is which.

I resorted to using the `x-axis-titles` and `y-axis-titles` to differentiate the graphs.  This method breaks when the user has two graphs with the same `x-axis-title` and `y-axis-title`.

Example code:
```
### Return x-axis title of figure object
def figure_xaxis_title(figure):
    return figure['layout']['xaxis']['title']

### Return y-axis title of figure object
def figure_yaxis_title(figure):
    return figure['layout']['yaxis']['title']



### A function used in a callback with dcc.store to store the click history of some data
# passed_data -> passed in data
# figure -> plotly figure object
# stored_data -> some list containing the history of clicks e.g [figure1, figure2, figure3, figure4] 
def figure_axis_comparison(passed_data, figure, stored_data):
    if figure_xaxis_title(figure) == 'Continents':
        return [passed_data, None, None, None]
    elif figure_xaxis_title(figure) == 'Country':
        stored_data[1] = passed_data
    elif figure_xaxis_title(figure) == 'Year' and figure_yaxis_title(figure) == 'Life Expectancy (Years)':
        stored_data[2] = passed_data
    elif figure_xaxis_title(figure) == 'Year' and figure_yaxis_title(figure) == 'GDP per Capita ($)':
        stored_data[3] = passed_data
    return stored_data`

### Code block that returns some figure object depending on the current graph when pressing the back button
       if figure_xaxis_title(figure) == 'Continents':
            figure = stored_figure_data[0]
        elif figure_xaxis_title(figure) == 'Country':
            figure = stored_figure_data[0]
        elif figure_xaxis_title(figure) == 'Year' and figure_yaxis_title(figure) == 'Life Expectancy (Years)':
            figure = stored_figure_data[1]
        elif figure_xaxis_title(figure) == 'Year' and figure_yaxis_title(figure) == 'GDP per Capita ($)':
            figure = stored_figure_data[2]
        return figure
```

Here is the code I wrote: https://github.com/plotly/dash-customer-success/blob/matthewchan15-recipes/apps/reciepes/dash_drilldown/app.py (feel free to ask for permission to the repo if you need it).

Another user who produced the drill down effect in Dash: 
https://community.plot.ly/t/drill-down-function-for-graphs-embedded-in-dash-app/12290/12

Example of drill down in Dash using callbacks:
![drill_down_app](https://user-images.githubusercontent.com/33464965/55591483-9c481980-5703-11e9-9a80-f1f3a91406e2.gif)

**Comment by chriddyp** [comment]
> I resorted to using the x-axis-titles and y-axis-titles to differentiate the graphs. This method breaks when the user has two graphs with the same x-axis-title and y-axis-title.

We can keep track of how "deep" we are in the drill down by using a `Store`'s `State` as an accumulator: pushing `clickData` as we go further down. Now that I think about this more, I'm not sure if we need anything more than that - we'll know what the axis title is by knowing how far deep we are. I'll try out an example and loop back.

**Comment by matthewchan15** [comment]
Clean solution implemented with Plotly Express:

```
import dash
from dash.dependencies import Input, Output, State
import dash_core_components as dcc
import dash_html_components as html
import pandas as pd
import plotly_express as px

DF = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/gapminderDataFiveYear.csv')

DRILLDOWN_FILTERS = [
    'continent',
    'country',
    'year'
]

app = dash.Dash(__name__)
app.layout = html.Div([
    dcc.Store(id='drilldown', data=[]),
    html.Button(
        "back",
        id='back'),
    dcc.Graph(id='graph')
])

@app.callback(
    Output('drilldown', 'data'),
    [Input('graph', 'clickData'),
    Input('back', 'n_clicks')],
    [State('drilldown', 'data')]
)
def update_drilldown_data(click_data, n_clicks, drilldown_values):
    if 'clickData' in dash.callback_context.triggered[0]['prop_id']:
        if len(drilldown_values) == len(DRILLDOWN_FILTERS) - 1 or click_data == None:
            raise dash.exceptions.PreventUpdate
        drilldown_values.append(click_data['points'][0]['x'])
    elif 'n_clicks' in dash.callback_context.triggered[0]['prop_id'] and click_data != None:
        drilldown_values.pop()
    return drilldown_values


@app.callback(
    Output('graph', 'figure'),
    [Input('drilldown', 'data')])
def update_figure(drilldown_values):
    dff = DF
    iterator = 0
    for (i, column) in enumerate(drilldown_values):
        dff = dff[dff[DRILLDOWN_FILTERS[i]] == drilldown_values[i]]
        iterator = i + 1
    return px.bar(
        dff,
        x=DRILLDOWN_FILTERS[iterator],
        y='lifeExp',
    )

if __name__ == '__main__':
    app.run_server(debug=True)
```

**Comment by Hassan-Ibrahim** [comment]
Hi everyone! i just wanna ask that is there any way that the back button will appear only when we drill down to the graph.

**Comment by Hassan-Ibrahim** [comment]
Hi @mtwichan! I just wanna ask that is there any way that the back button will appear only when we drill down to the graph.

**Comment by alexcjohnson** [comment]
@Hassan-Ibrahim You could give the second callback a second output, `Output('drilldown', 'style')` and set it to `{'display': 'none'}` if `drilldown_values` is falsy, or `None` otherwise.

**Comment by ShaheenSolwa** [comment]
Hi @mtwichan @Hassan-Ibrahim 

I am working on a code based on this specific drilldown in python. I am stuck at an issue where I need to display multiple columns of data in the form of a bar chart after a click.

Any advice on how to accomplish this would be of great help!

Thanks in Advance!
