### ISSUE TITLE
dcc.Input with type="number" unable to clear

### ISSUE THREAD

**Issue by oliverbrace** [plotly/dash-core-components#513]
When one has dcc.Input with type="number"  it is not possible to clear what is inside the input like with dcc.Input with type="text". I assume this is because deleting it so nothing is contained sets it to "" which is not in the list of allowed values for numbers. 
However this results in placeholder text being irritativable in "input type number" once text has been inserted. 

I also have input boxes, which when blank, uses a default value within the code. Currently I have to create a button and a callback which clears the input box, however .

HTML input type number does allow for blank values (and the letter e), however something is then changing it to be 0. 

I feel that the functionality should be the same as hmtl.input and allow for "" to be an accepted value.

**Comment by alexcjohnson** [comment]
related: #455
