### ISSUE TITLE
Graph config defaults don't match plotly.js

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/dash-core-components#514]
`Graph` sets its own `config` defaults [here](https://github.com/plotly/dash-core-components/blob/b1932f9aaaea89f099c17be0ce8f1d9e0538379a/src/components/Graph.react.js#L586-L622) - but this has no mechanism to keep up to date with plotly.js, and in fact it's out of date already in at least one respect, `scrollZoom`, as of https://github.com/plotly/plotly.js/pull/3422

We should either remove those defaults entirely, or programmatically match them to plotly.js.

There's a related problem: if you override a *piece* of the config, the rest of the default gets dropped. So for example right now if you were to set something unrelated like `showLink: true`, the `scrollZoom: false` would be dropped - and set to the new plotly.js default!

cc @nicolaskruchten @michaelbabyn - discovered while researching https://github.com/plotly/plotly.js/issues/3738

**Comment by nicolaskruchten** [comment]
Cc @wbrgss

**Comment by alexcjohnson** [comment]
Did a little investigation of the current `Graph.defaultProps` values vs plotly.js:
- Only one value is provided but does NOT match plotly.js, the aforementioned `scrollZoom`.
- A whole bunch of entries aren't present at all:
  - plotlyServerURL
  - responsive
  - showSendToCloud
  - toImageButtonOptions
  - watermark
  - setBackground
  - logging
  - globalTransforms
  - locale
  - locales

For the moment I'll make a PR to remove the defaults and add documentation for the new entries. Later - unless it's quick and I can get it in for the upcoming release - I'll make another PR to test that these keys continue to match when we upgrade plotly.js.

**Comment by alexcjohnson** [comment]
Actually I'm not going to include `setBackground`, `logging`, or `globalTransforms` - these either won't work or aren't serializable, if you wanted to use them you'd need to subclass `Graph`.

**Comment by alexcjohnson** [comment]
Closing - #515 fixes the bug by removing the nested defaults, and includes a test that `propTypes` for `Graph` has the right keys from the plotly.js schema.
