### ISSUE TITLE
dcc.Tabs "Content as Tab Children" breaks with dash >= 0.40.0

### ISSUE THREAD

**Issue by wbrgss** [plotly/dash-core-components#522]
To be more specific, could be the `dash-renderer` version that is included with `0.40.0`. With version `<= 0.39.0` Tab Children appear to work as intended.

A reproducible example is in the docs themselves. See **Method 2. Content as Tab Children** and try to click on "Tab two" or "Tab three":
https://dash.plot.ly/dash-core-components/tabs

**With callbacks — works great**
![tabs-with-callbacks](https://user-images.githubusercontent.com/9068290/55991648-c0ae7380-5c78-11e9-903c-3ab772171ef9.gif)

**With `children` (broken; tabs don't respond to click events)**
![tabs-wo-callbacks](https://user-images.githubusercontent.com/9068290/55991660-c4da9100-5c78-11e9-8c4e-fbb90038a513.gif)

Possibly related to #460, but I don't think so.

**Comment by byronz** [comment]
looks like need a click on tab and snapshot scenario to cover that

**Comment by wbrgss** [comment]
Hold that thought, I'm not seeing this in the docs anymore...investigating

**Comment by wbrgss** [comment]
I'm finding it difficult to replicate this error consistently. This is what I'm seeing in the dev console when it's loaded in a broken state:

![image](https://user-images.githubusercontent.com/9068290/55995005-59e18800-5c81-11e9-9c46-0d460f43005e.png)

**Comment by byronz** [comment]
@wbrgss  do you think this issue is still valid? cannot reproduce here https://dash.plot.ly/dash-core-components/tabs

**Comment by wbrgss** [comment]
I believe this is fixed now; not sure which Dash release fixed it though. Closing.
