### ISSUE TITLE
"TypeError: H is not a function" when selecting scatter points

### ISSUE THREAD

**Issue by slishak** [plotly/dash-core-components#526]
I'm not sure if this is a bug in Dash or Plotly.js, but seeing as I can't reproduce it when saving the figure with `plotly.offline.plot`, I'll put it here.

Whenever I select scatter points in a Dash app, I've started getting the following error:

![image](https://user-images.githubusercontent.com/12515343/56133940-d29c5900-5f8d-11e9-9db2-36f3fc503562.png)

It doesn't seem to affect the running of the app, any callbacks are still fired for the selected points.

Simplest example to reproduce:

```python
import dash
import dash_core_components as dcc
import dash_html_components as html
import random

app = dash.Dash()

app.layout = html.Div([
    dcc.Graph(
        id='example-graph',
        figure={
            'data': [
                {
                    'x': [random.random() for _ in range(20)],
                    'y': [random.random() for _ in range(20)],
                    'type': 'scatter',
                    'mode': 'markers'

                }
            ],
            'layout': {
                'dragmode': 'select'
            }
        }
    )
])

if __name__ == '__main__':
    app.run_server(dev_tools_serve_dev_bundles=True)
```

Versions:
```
dash==0.41.0
dash-core-components==0.46.0
dash-html-components==0.15.0
dash-renderer==0.22.0
plotly==3.7.1
```

Also, for some reason I'm not getting the dev bundles when I set `dev_tools_serve_dev_bundles=True`, so sorry if the stack trace isn't very helpful!

**Comment by alexcjohnson** [comment]
Yes, this should not affect anything, and will be fixed when we update plotly.js to 1.47.1 or greater - https://github.com/plotly/plotly.js/pull/3755

I doubt we'll make a patch release just for this though, probably we'll wait for 1.48 and include this in the next minor dash release.

**Comment by slishak** [comment]
OK, thanks very much! Didn't realise that was the same issue. And understood about the dev bundle, makes sense.

**Comment by slishak** [comment]
This has been fixed by a plotly.js update.
