### ISSUE TITLE
datepicker - `clearable` False can still clear date

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash-core-components#53]
As reported in https://community.plot.ly/t/solved-datepicker-in-dash/4816/9?u=chriddyp:

> Also, with clearable=False backspace can still clear date, but on action it will pop back in. I think that date field should be editable only from calendar view with clearable=False, or add something like editable? (when with_portal=True it is not reproducible as backspace does not fall ‘behind’ portal)

**Comment by alishobeiri** [comment]
The clearable prop refers to whether a clear button is present in the datepicker:

clearable=True
![image](https://user-images.githubusercontent.com/18422723/29198599-8bdffba0-7e13-11e7-9d10-98b6f278cc8c.png)

clearable=False
![image](https://user-images.githubusercontent.com/18422723/29198613-a74f13a8-7e13-11e7-832c-2bcac841ffd8.png)

I think the name might be causing the confusion, I'll try to fix that, I'm not sure about being able to add an `editable` prop though.

**Comment by alishobeiri** [comment]
PR #58 fixes this by clarifying the description of clearable
