### ISSUE TITLE
Stop changing page title to 'Updating...' when doing a graph update

### ISSUE THREAD

**Issue by jdlongman** [plotly/dash-core-components#546]
When live-updating a graph (dcc.Graph updated with dcc.Interval), every time an update is made, the title of the page flickers to 'Updating...'. 
When calling updates every second this essentially means that the browser tab will keep flickering this message on and off, which is incredibly annoying. 
Is there a means to disable this from happening? If not, one is needed.

**Comment by fheilz** [comment]
Any update to this?

**Comment by stlehmann** [comment]
I agree. Especially for displaying livedata the flickering of the title makes the whole webapp very noisy. Would be great if one could disable this on demand.

**Comment by srinathsrk76** [comment]
+1 for feature request!

**Comment by stlehmann** [comment]
This PR addresses this issue and allows to disable the change of the title on updating: https://github.com/plotly/dash/pull/1315

**Comment by chriddyp** [comment]
> Is there a means to disable this from happening? If not, one is needed.

This is now complete as of Dash 1.14.0 thanks to @stlehmann 🙂 

See https://community.plotly.com/t/dash-v1-14-0-released-update-the-tabs-title-removing-the-updating-messages-updated-datatable-link-behavior/43080/ & https://dash.plotly.com/external-resources for details.
