### ISSUE TITLE
Merge Markdown and SyntaxHighlighter, and import separately

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/dash-core-components#559]
Two-part issue:
- @wbrgss has a way to work syntax highlighting directly into `Markdown`, so we can drop the `SyntaxHighlighter` component altogether.
- Since the code for these two (or one) components is by far the largest piece of the dcc JS bundle, it would be great to separate that out. My thought is we can require `Markdown` to be imported separately - ie you can't use it directly as `import dash_core_components as dcc -> dcc.Markdown` - instead you need to do `from dash_core_components.markdown import Markdown`, and in the file `markdown.py` we would modify `dcc._js_dist` - similar to how `dash-cytoscape` has `load_extra_layouts` https://github.com/plotly/dash-cytoscape/blob/541f9a52e25f44f0ad5eb165ba488a9179f847c7/dash_cytoscape/__init__.py#L52-L95

**Comment by wbrgss** [comment]
Closed in #562
