### ISSUE TITLE
RangeSlider has no attribute of 'size' as Slider has

### ISSUE THREAD

**Issue by out-sider** [plotly/dash-core-components#560]
I want to filter the data using RangeSlider to set min and max. And I have three value that needs to be controlled, so I want to put all three RangeSlider into a dash_html_components.Table, but the sliders are just too long and overlap with each other.
![dash](https://user-images.githubusercontent.com/8955160/58761125-13b6ef80-8573-11e9-96f2-44597ed903c2.png)

After searching, I found that Slider has size attribute, but RangeSlider doesn't. Anyway to solve it?

`app.layout =html.Div([
        html.Table([
            html.Tr([html.Td('gender',style={'text-align': 'center'}),
                    html.Td('age',style={'text-align': 'center'}),
                    html.Td('BMI',style={'text-align': 'center'})]),
            html.Tr([
                html.Td(dcc.RangeSlider(id='gender_slider',marks={0:'F',1:'M'},min=0,max=1,value=[0,1]),style={'width':'10%'}),
                html.Td(dcc.RangeSlider(id='age_slider',marks={age_min:str(age_min),age_max:str(age_max)},
                    min=age_min,max=age_max,value=[age_min,age_max]),style={'width':'40%'}),
                html.Td(dcc.RangeSlider(id='BMI_slider',marks={BMI_min:str(BMI_min),BMI_max:str(BMI_max)},
                    min=BMI_min,max=BMI_max,value=[BMI_min,BMI_max]),style={'width':'40%'})
            ])
        ],style={'width':'90%'})
![TIM截图20190602201603](https://user-images.githubusercontent.com/8955160/58761129-2b8e7380-8573-11e9-9cc8-1609dc7b880a.png)

        )
    ])`

**Comment by mmartinsky** [comment]
I think you can fix this via some plain CSS.

```
import dash
from dash.dependencies import Input, Output, State
import dash_html_components as html
import dash_core_components as dcc

app = dash.Dash()

age_min = 20
age_max = 80

app.layout = html.Div(
    [
        dcc.RangeSlider(id="gender", marks={
                        0: 'F', 1: 'M'}, min=0, max=1, value=[0, 1], className="margin10"),
        dcc.RangeSlider(id="age", marks={age_min: str(age_min), age_max: str(age_max)},
                        min=age_min, max=age_max, value=[age_min, age_max], className="margin10"),
        dcc.RangeSlider(id="BMI", marks={
                        0: 'F', 1: 'M'}, min=0, max=1, value=[0, 1], className="margin10"),
    ],
    style={"display": "grid", "grid-template-columns": "10% 40% 50%"}
)


if __name__ == '__main__':
    app.run_server(debug=True)
```

and setting the CSS for the .margin10 class:
```
.margin10 {
    margin-left: 10px;
    margin-right: 10px;
}
```

![image](https://user-images.githubusercontent.com/9168958/59168330-5e9cae00-8b03-11e9-87d8-ee9924c82411.png)

**Comment by out-sider** [comment]
@mmartinsky Thank you, it works.

I plan to use Dash as a high level wrapper of interactive web plot lib, but it turns out I have to pick HTML up again and learn CSS. So, maybe the Plotly team can focus on simplifying the usage in the continuing developing?
