### ISSUE TITLE
Feature request: pass className to RadioItems

### ISSUE THREAD

**Issue by jamestwebber** [plotly/dash-core-components#57]
I've got a couple RadioItems controls for a plot, arranged like so:

<img width="580" alt="screen shot 2017-08-12 at 11 52 17 am" src="https://user-images.githubusercontent.com/963647/29243479-ccf488c6-7f54-11e7-883c-34641e6d9535.png">

I originally tried to just pass `className="six columns"` to the RadioItems component but that's not an accepted keyword (for some reason&mdash;I thought it would be inherited). So as a workaround I wrapped them in extra `div`s with the `six columns` class. Given that a RadioItems component renders as a `div` anyway, it would be a wee bit cleaner to be able to pass the class in directly to that `div` and save a layer of layout boilerplate.

I don't know if the same issue applies to any other components. It seems to work in some cases (e.g. `Dropdown` takes `className` as a keyword) but in general any component that ends up wrapped in its own `div` could benefit from this.

Thanks again for all your hard work on this package!

**Comment by chriddyp** [comment]
Great suggestion @jamestwebber ! Fixed in #60, available in `v0.12.4`. Upgrade with
```
pip install dash-core-components==0.12.4
```
