### ISSUE TITLE
Migrate and Enhance - DatePickerRange integration tests 

### ISSUE THREAD

**Issue by byronz** [plotly/dash-core-components#581]
We have a couple of `DatePickerRange` related bugs and plan to release some bug fixes in Dash 1.1.0. 
it's good timing to migrate the relevant tests and cover more missing corners:

-  find out the reported issues in github and community threads
- check out the properties list defined in https://dash.plot.ly/dash-core-components/datepickerrange

find out the common traits about the issues users have encountered. and add them as test case to improve our test coverage. 

the tests could be placed under `integration/date_picker_range/`

**Comment by Marc-Andre-Rivet** [comment]
@byronz Seems to me this is supplanted by #600 and could be closed.
