### ISSUE TITLE
make all dependencies as assets

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/dash-core-components#597]
We should be able to treat the plotly.js file as a build artifact, such that upgrading it is as simple as:
- update the version number in `package.json` -> `devDependencies`
- add a changelog note
- do NOT commit changes in the `dash_core_components` dir

Then its build step would consist of:
- read the version out of `node_modules/plotly.js/package.json` (don't get it from our own package.json, in case `npm i` hasn't been called)
- delete old `dash_core_components/plotly-*.js`
- copy `node_modules/plotly.js/dist/plotly.min.js` into `dash_core_components/plotly-<version>.min.js`
- update `dash_core_components/__init__.py`

Aside from simplifying updates, this would prevent various possible errors, and ensure py/R consistency (plotly.js is already treated as a build artifact as far as the R package is concerned)

**Comment by byronz** [comment]
@alexcjohnson , chatted with @rpkyle today, I will take this issue as placeholder for plotly.js and also hightlight.js and css, the current repo has replicated js bundles, and the R script copied the bundles from the dash_core_component repo, ideally, we should have a common assets folder for all languages, a symbolic link might be the way for that, I will investigate and update the status here
