### ISSUE TITLE
[BUG] dcc.DatePickerSingle does not display the full calendar 

### ISSUE THREAD

**Issue by luisJuarezJuarez** [plotly/dash-core-components#625]
in current release of dash the date picker does not displays the complete calendar and some dates are even not elegible though you can still write them down. i suppose this is a css issue.
As example of this issue try to select 31/08/2019 
![image](https://user-images.githubusercontent.com/46457356/64035604-725a1e00-cb0e-11e9-8f0a-86b2187bedbe.png)

in a previous version of dash this worked!

![image](https://user-images.githubusercontent.com/46457356/64129834-da616c00-cd7b-11e9-899d-884568a929e2.png)

**Comment by wbrgss** [comment]
I think this is a duplicate. Even though this issue was created at an earlier date, I'm closing it in favour of #658 as it has more discussion.
