### ISSUE TITLE
[BUG] data-dash-is-loading attribute not updated on Graph

### ISSUE THREAD

**Issue by fl4p** [plotly/dash-core-components#632]
In `dash-0.41.0` the `data-dash-is-loading` attribute always stays at `true` value on Graph elements.

**Comment by ethanopp** [comment]
Has there been any update on this? I am experiencing the same issue on 1.9.1

**Comment by ohaibbq** [comment]
@fl4p @ethanopp I have this patch if you want to try it out-
https://github.com/plotly/dash-core-components/pull/837

**Comment by ned2** [comment]
It's working for me!

**Comment by HammadTheOne** [comment]
Closed via #837
