### ISSUE TITLE
soft link to LICENSE.txt makes the github license invalid

### ISSUE THREAD

**Issue by byronz** [plotly/dash-core-components#637]
![Screen Shot 2019-09-04 at 5 03 08 PM](https://user-images.githubusercontent.com/1394467/64291343-ed1fa080-cf35-11e9-98b7-35319322f852.png)

@rpkyle  your change of soft link makes the license tab on github invalid. Can you see how to fix that?

**Comment by rpkyle** [comment]
@byronz https://github.com/plotly/dash-core-components/pull/638
