### ISSUE TITLE
metadata.json defaultValue formatting

### ISSUE THREAD

**Issue by cpsievert** [plotly/dash-core-components#68]
If it isn't too much trouble, it'd be much easier for me to parse the defaultValues fields if we made two changes:

1. Single-quote rather than double-quote JSON values (e.g., `"{}"` -> `'{}'`, `"[]"` -> `'[]'`, `"''"` -> `'""'`)
2. Quote JSON object keys (e.g., [`"{data: [], layout: {}}"` -> `'{"data": [], "layout": {}}'`](https://github.com/plotly/dash-core-components/blob/1786bdd2aee616d45ed6d99f8103739b123d5f6f/dash_core_components/metadata.json#L920))

Related to https://github.com/jeroen/jsonlite/issues/197

**Comment by cpsievert** [comment]
I've found a reasonable workaround https://github.com/jeroen/jsonlite/issues/197#issuecomment-326342495, so feel free to ignore

**Comment by chriddyp** [comment]
OK great. FYI I'm using react-docgen (https://github.com/reactjs/react-docgen) so changes like these are hard to make
