### ISSUE TITLE
dcc.Graph in dcc.Loading component isn't working right

### ISSUE THREAD

**Issue by Marc-Andre-Rivet** [plotly/dash-core-components#684]
See https://github.com/plotly/dash-core-components/issues/672#issuecomment-542784762

> This might be indicative of a deeper rendering problem within the loading component - why are we creating the graph twice?

**Comment by chriddyp** [comment]
Related https://github.com/plotly/dash-core-components/issues/756. There have also been many community-reported issues: 
- https://community.plotly.com/t/choroplethmapbox-hover-problem/33218/4
- https://community.plotly.com/t/dash-graph-showing-an-output-which-is-based-on-previous-iteration-of-input/36726/7
