### ISSUE TITLE
Include / exclude props that dcc.Loading component reacts to

### ISSUE THREAD

**Issue by Marc-Andre-Rivet** [plotly/dash-core-components#709]
From community issue https://community.plot.ly/t/loading-state-argument-in-dcc-loading/31936

- Probably requires https://github.com/plotly/dash/issues/893 to be fixed
- As part of this issue, we would want to hide `loading_state` from the generated API for the components -- this prop is generated by the renderer and it makes no sense for users to try and do anything with it
- The loading component would now need the list of id/props that are being processed instead of a single prop https://github.com/plotly/dash/blob/dev/dash-renderer/src/TreeContainer.js#L322

New prop(s) for dcc.Loading
- Allow users to provide an inclusion/exclusion list of props that the component will react to to enable it's "loading state"

**Comment by rredburn** [comment]
Seems like this is the same as:  https://github.com/plotly/dash/issues/951

**Comment by HedgeShot** [comment]
This would be really nice. My use case is the following: long callback that returns a "children" with a child that is link to another callback. It makes sense to have dcc.Loading around the long callback but it doesn't when updating the child. At the moment, dcc.Loading is triggered with both callbacks. Having the possibility to exclude some ids would solve the issue.

**Comment by luggie** [comment]
any news on this so far?

**Comment by KingSolomonEpstein** [comment]
I'm also trying to use dcc.Loading and dcc.Interval together. It... isn't going well. Is this likely to be addressed or should the dcc.Loading documentation be updated to acknowledge this limitation?

**Comment by CNFeffery** [comment]
@Marc-Andre-Rivet  @chriddyp What's new about this feature so far

**Comment by huong-li-nguyen** [comment]
Has there been any update on this?

**Comment by CNFeffery** [comment]
@huong-li-nguyen I suggest you to use my relative components:

https://fac.feffery.tech/AntdSpin
https://fac.feffery.tech/AntdSkeleton
https://fac.feffery.tech/AntdCustomSkeleton
https://fuc.feffery.tech/FefferyTopProgress

**Comment by florian6973** [comment]
Still very interested by this feature

**Comment by Coding-with-Adam** [comment]
closed by #2760
