### ISSUE TITLE
Suggestion: explore webpack caching to speed up dash-core-components builds

### ISSUE THREAD

**Issue by rpkyle** [plotly/dash-core-components#719]
Currently, it takes several minutes to execute `npm run build` when rebuilding `dash-core-components`. 

It would likely improve the developer experience if we could enable caching for `webpack` modules/chunks to reduce the time required.

@Marc-Andre-Rivet

**Comment by Marc-Andre-Rivet** [comment]
This was fixed by https://github.com/plotly/dash-core-components/pull/716. Closing.
