### ISSUE TITLE
0.13.0 breaks dcc.DatePickerRange

### ISSUE THREAD

**Issue by frogger72** [plotly/dash-core-components#76]
Wanted to use the latest for tabs.  But DatePickerRange's screen-reader only text is visible and displayed in large letters: "Press the down arrow key to interact with the calendar and select a date. Press the question mark key to get the keyboard shortcuts for changing dates." Also, a giant SVG arrow is generated between the date boxes that covers the full page

**Comment by chriddyp** [comment]
Thanks @frogger72 ! Fixed in `v0.13.0-rc7`
