### ISSUE TITLE
dcc.Location should not fire callback for pathname if the href changed

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash-core-components#769]
Reproducible eaxmple:

```python
import dash
from dash.dependencies import Input, Output
import dash_core_components as dcc
import dash_html_components as html
import datetime
import numpy as np
print(np.__version__)

app = dash.Dash(__name__)

app.layout = html.Div([
    dcc.Location(id='location'),

    html.A('Anchor Link 1', href='#div'),
    html.Span(' - '),
    html.A('Anchor Link 2', href='#div-2'),

    html.Div(id='div'),
    html.Div(id='div-2')
])


@app.callback(Output('div', 'children'), [Input('location', 'pathname')])
def update_path(path):
    print(path)
    return str(datetime.datetime.now())


app.run_server(debug=True)
```

Clicking between the links fires the callback. The callback should not be fired because the `pathname` did not change, only the `href` changed.

It looks like we already have logic that detects _which_ property changed: https://github.com/plotly/dash-core-components/blob/b35a560712b74a1bccdf4ca1627c6a3095584b60/src/components/Location.react.js#L60-L70

I suspect that we just need to apply that logic to the `setProps` call below: https://github.com/plotly/dash-core-components/blob/b35a560712b74a1bccdf4ca1627c6a3095584b60/src/components/Location.react.js#L87-L97

A fix for this is needed in order to provide anchor links in a sidebar in the dash docs. I'm working on this in https://github.com/plotly/dash-docs/pull/802.

cc @Marc-Andre-Rivet  - This might be another nice one for @HammadTheOne ⚾️

**Comment by chriddyp** [comment]
(Related https://github.com/plotly/dash-core/issues/89 & https://github.com/plotly/dash-docs/pull/735, but https://github.com/plotly/dash-docs/pull/802 is the main PR that has its own self-contained sidebar with anchor links)

**Comment by AHMatsWillemsen** [comment]
Hi, thanks for this! We found this bug while developing a multi-page app with one part listening for the pathname changes, and one part for the search-changes, resulting in double callbacks for the search callback. In what version do you expect this fix to be included? We can then remove a custom component.

**Comment by chriddyp** [comment]
@HammadTheOne  - this should be closed, right?

**Comment by HammadTheOne** [comment]
Yup, forgot to put the `closes` tag in the PR, but this is merged in.
