### ISSUE TITLE
dcc.Link should work with absolute paths

### ISSUE THREAD

**Issue by Marc-Andre-Rivet** [plotly/dash-core-components#771]
In order for dcc.Link click events to behave like HTML anchors,

https://github.com/plotly/dash-core-components/blob/dev/src/components/Link.react.js#L47

```
window.location.pathname = href;
```

needs to be modifed to 
```
window.location= href;
```

For example

```
dcc.Link(
  href='https://www.google.com',
  refresh=True,
  children=['www.google.com']
)
```
will change the path to `http://localhost/https://www.google.com` instead fo opening `https://www.google.com`

**Comment by wbrgss** [comment]
Related to #750 — I wonder if this proposed change would allow for "hotlinking" to anchor links with a URL, via an `id`, instead of just clicking e.g. 

https://en.wikipedia.org/wiki/Python_(programming_language)#Expressions
