### ISSUE TITLE
dcc.Link: Use `href` as `children` if no children are defined

### ISSUE THREAD

**Issue by Marc-Andre-Rivet** [plotly/dash-core-components#772]
With HTML anchors, users are forced to provide a displayed content for the anchor, which can be as simple as the href itself..

```
<a href='myurl'>myurl</a>
```

1:1 correspondance in dcc.Link forces users to do the same thing:
```
dcc.Link(
  href='myurl',
  children=['myurl']
)
```

Defaulting to href for inner content if no children is defined provides a default behavior that will be acceptable in certain situations and will simplify usage.

**Comment by alexcjohnson** [comment]
Perhaps the other way as well, use `children` as `href` - that way you can do `dcc.Link(myurl)` and it'll behave reasonably.

**Comment by Marc-Andre-Rivet** [comment]
It's possible to use anything as a dcc.Link child and the whole thing becomes clickable, while href is a string and can be used safely as a child, the same can't be said about children.

```
    dcc.Link(
        href='/sub-path',
        refresh=True,
        children=[html.Div('Hello'), html.Div('World')]
    ),
```

**Comment by alexcjohnson** [comment]
sure, but if `children` *happens* to be just a string, we might as well copy it back to `href`.

**Comment by Marc-Andre-Rivet** [comment]
Yes. But it lends itself to a `if..else..` logic that can be confusing. Not opposed per say, just want to make sure we agree on the limitations / logic leakage if we decide to support it.

**Comment by alexcjohnson** [comment]
Fair enough - and it could be confusing if you start with just `children` and want to switch to different text/elements - you have to make two changes: move the `children` string into `href` and then provide the new `children`. Then we can also do #773 🎉
