### ISSUE TITLE
DatePickers should return a date string, not a datetime string

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash-core-components#781]
Currently, `DatePickerRange` returns a string like `2015-01-10T00:00:00` and `DatePickerSingle` returns a string like `2015-01-10 00:00:00`

This requires parsing logic for `DatePickerRange` like
```
date = dt.strptime(date.split('T')[0], '%Y-%m-%d')
```
which is slightly different than what is required for `DatePickerSingle`:
```
date = dt.strptime(date.split(' ')[0], '%Y-%m-%d')
```

No matter what, they should give consistent values. However, I think that they should just not include the _time_ portion of the string given that there is no way to select time from these components.

**Comment by alexcjohnson** [comment]
Can we get a sample app to clarify what we're talking about here? I see both of these components formatting new dates as `YYYY-MM-DD` so is it only callback- or layout-provided dates that get this behavior somehow?

**Comment by harryturr** [comment]
@alexcjohnson @Marc-Andre-Rivet 
Here is a simple example app showing the behaviour of the datepickers currently. 

You can see that when you specify a date without a time in the layout or callback, for example `datetime(2020, 1, 3)`, the `date`, `start_date`, or `end_date` props will have the time stored, eg `2020-01-03T00:00:00`.

When selecting a new date from the UI, there will be no time stored since `onDateChange` [strips the time and applies setProps](https://github.com/plotly/dash-core-components/blob/6e325437b7812c1985770dc08fa53c7da670758f/src/fragments/DatePickerSingle.react.js#L30).
[datepickers.zip](https://github.com/plotly/dash-core-components/files/5314214/datepickers.zip)

**Comment by alexcjohnson** [comment]
OK so our [PlotlyJSONEncoder serializer](https://github.com/plotly/plotly.py/blob/73651942b51587086da1eee53f67995f28d68ee3/packages/python/plotly/_plotly_utils/utils.py#L13) for the [`datetime.datetime` type](https://github.com/plotly/plotly.py/blob/73651942b51587086da1eee53f67995f28d68ee3/packages/python/plotly/_plotly_utils/utils.py#L175) uses a `T` separator (via `.isoformat()`), how / when do we get the space separator? When you call `str(datetime(2020, 1, 3))` explicitly? Or is there something else internal that will do this?

The easy answer here (== docs) is "why are you using a datetime when you want a date? Just use `datetime.date` and there's no time part to worry about." If you already have a `datetime.datetime` object, convert it with `.date()`.

I'm a little skeptical of "fixing" the datetime strings users pass in by removing the time part, feels a bit magical and invasive. I could be convinced though, and perhaps the prop sanitation idea would be the cleanest - defined by a component but invoked by the renderer?

**Comment by Marc-Andre-Rivet** [comment]
Guess it’s way too late to tighten the date type check without a major bump to 2.x based on our approach so far… the fact that we use `react-docgen`'s knowledge of prop-types for docs generation is at issue here.. validating the type for `/^\d{4}-\d{2}-\d{2}$/ is trivial but breaks docs.. - looking at the react-docgen source, doesn't seem like we have a clean way to add our own custom types that it would pick up correctly for our other purposes. With devtools in place we can in theory do that validation anywhere.. like in the `render` or `UNSAFE_componentWillReceipeProps` function if we feel like it and throw an exception similar to what prop-types would throw.. For future components we should probably consider doing finer-than-type props checking this way.. really does seem like the short term fix here is docs only and we can defer sanitation/silent stuff for a later discussion if a clear case emerges.
