### ISSUE TITLE
update Dropdown to accept maxHeight prop

### ISSUE THREAD

**Issue by pfbuxton** [plotly/dash-core-components#785]
It would be very useful (especially with long lists) to be able to change the height of the Dropdown - the default settings allow for 5.7 options to be shown (optionHeight=35 and maxHeight=200).

A similar issue has been resolved (https://github.com/plotly/dash-core-components/pull/552) to allow the optionHeight prop to be passed, i.e. 
```python
dcc.Dropdown(
    id = 'dropdown_id',
    options = my_options,
    optionHeight = 35,
    # maxHeight = 80
),
```
so allow maxHeight to be passed in the same way.

See https://github.com/bvaughn/react-virtualized-select/blob/master/README.md#react-virtualized-select-props

**Comment by marcsiebs** [comment]
This would be very helpful to me as well

**Comment by lacrendic** [comment]
It definitely would be very helpful. Is there any workaround? I don't want all selected items to be displayed, there are too many at times

**Comment by pfbuxton** [comment]
@lacrendic I made this post a while ago when I didn't fully understand how dash worked. I now have a better understanding of how dash works and wanted to see if I could now fix this myself. Good news I made the dropdown longer:

![Capture](https://user-images.githubusercontent.com/4923588/105848150-7d043580-5fd6-11eb-891f-9e42f50c6774.PNG)

Here is the repository where I made the changes:
https://github.com/pfbuxton/dash-core-components

The changes involved:
1. Exposing the `maxHeight` prop
2. Changing this css file:
https://github.com/plotly/dash-core-components/blob/dev/src/components/css/react-select%401.0.0-rc.3.min.css

I don't understand how to change the css styling programmatically within Javascript (I simply don't have any more time to work on this at the moment). If anyone would like to pick this up and finish the job that would be nice.

To build and install a dash component you need to do this:
```terminal
npm run build
python3 setup.py build
python3 setup.py install
```

**Comment by PedroCanoM** [comment]
@pfbuxton, how did you manage to do it? I'm also trying to change the default maxHeigth. In fact, I've tried to build a custom dcc dropdown that includes this property with no success.  I tried to access to your repository, but it seems to have been deleted. 
I appreciate any kind of help.

**Comment by PedroCanoM** [comment]
As it is described here: https://community.plotly.com/t/dash-custom-dropdown-component/51293?u=pkane , I've maintained the multi-folder structure and the same error happens. I've used the dash-component-boilerplate repository.

**Comment by marchinidavide** [comment]
Any update on this?

**Comment by alexcjohnson** [comment]
We'd gladly accept a PR if someone would like to add this prop. Please note that this repo is no longer in use, dash core components are now part of the main [dash repo](https://github.com/plotly/dash/tree/dev/components/dash-core-components)
