### ISSUE TITLE
dcc.DatePickerRange end date calendar pop-up selects start date default upon initialization

### ISSUE THREAD

**Issue by frogger72** [plotly/dash-core-components#80]
It should start on the end-date default.  Very annoying for users if the two days are far apart (years)

**Comment by chriddyp** [comment]
Example:
![range-dates](https://user-images.githubusercontent.com/1280389/30834638-0753fa52-a222-11e7-80dc-5b6c17f265bd.gif)

Yeah, that is really annoying. I'll look into it. This might be an underlying issue with https://github.com/airbnb/react-dates

**Comment by chriddyp** [comment]
It looks like this issue is being considered in https://github.com/airbnb/react-dates/issues/48.

**Comment by chriddyp** [comment]
Found and posted what seems like a solution in https://github.com/airbnb/react-dates/issues/151#issuecomment-332044734

**Comment by frogger72** [comment]
Nice - thanks for looking into it so quickly!
