### ISSUE TITLE
disable autocomplete in dropdown by default

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash-core-components#808]
![image](https://user-images.githubusercontent.com/1280389/82741649-4b312580-9d09-11ea-978d-b1ffe3344c8a.png)

Here is one approach: https://github.com/JedWatson/react-select/issues/758, but not sure if those `inputProps` apply to the version that we're on.

**Comment by Migggz** [comment]
I have the same issue and `inputProps` not worked for me

**Comment by PCPbiscuit** [comment]
Try 
<Select isSearchable={false} />

Worked for me

**Comment by chriddyp** [comment]
Fixed in https://github.com/plotly/dash-core-components/pull/923 😌
