### ISSUE TITLE
Graph dimension problem with dcc.Loading — regression (?) in DCC 1.9.1

### ISSUE THREAD

**Issue by wbrgss** [plotly/dash-core-components#831]
Given a certain layout (I've tried to trim down to a minimal example as best I can), `dcc.Loading` causes its `dcc.Graph` children to not obey their set heights in CSS. 

In the below examples, I expect the Graph to be constrained within the purple boundary.

With the code below, with Dash 1.11.0 and Dash Core Components 1.9.1:

![image](https://user-images.githubusercontent.com/9068290/86860128-4692b780-c092-11ea-9fa7-685d7f871a48.png)

With Dash 1.11.0 and Dash Core Components 1.9.0 (or simply Dash <= 1.10.0):

![image](https://user-images.githubusercontent.com/9068290/86860208-6b872a80-c092-11ea-976a-8b844d3ca576.png)

Unfortunately, there was one rule I had to put in an `/assets/style.css`, I left a comment in the app.

**app.py**

```py
import dash
import dash_html_components as html
import dash_core_components as dcc

app = dash.Dash(__name__)

app.layout = html.Div(
    children=[
        # this outer div is necessary to reproduce
        html.Div(
            dcc.Loading(
                # This must load CSS from an external file
                # in /assets via the className
                # style={"height": "100%"} won't have the same effect
                className="loading-container",
                children=dcc.Graph(
                    style={"height": "100%"},
                    figure={
                        'data': [{
                            'x': [1, 2, 3, 4],
                            'y': [4, 1, 6, 9],
                            'line': {'shape': 'spline'}
                        }]
                    }
                ),
            ),
        )
    ],
    style={
        # these rules are necessary to reproduce
        "display": "flex",
        "maxHeight": "30vh",
        # the below two rules are for visual demo purposes
        "padding": "15px",
        "background": "purple"
    },
)

if __name__ == "__main__":
    app.run_server(debug=True)
```

**style.css**
```css
.loading-container {
    height: 100%;
}
```

**Comment by wbrgss** [comment]
My guess is that this is coming from https://github.com/plotly/dash-core-components/pull/740. If you replace the `dcc.Loading` with an `html.Div` in the example above, the problem goes away. I welcome @alexcjohnson to take a look at this please, as you recently got your hands dirty with graph dimensions, and it looks like you were the main reviewer on/a contributor to #740 :slightly_smiling_face:

**Comment by wbrgss** [comment]
Some more details after some investigation:

>  ```py
>    # This must load CSS from an external file
>    # in /assets via the className
>    # style={"height": "100%"} won't have the same effect
> ```

The reason or this is that `dcc.Loading` doesn't seem to add inline styles on its outermost container when it's given a `style` prop, even though it _accepts_ this prop. It adds the inline styles on the `Spinner` component but not on the outermost container, and in a nested layout like this **all** of the containers in the hierarchy need to have e.g. `height: inherit` or `height: 100%`. The empty style object on the outermost div (that gets the conditional `hiddenContainer` style) here breaks that chain:

https://github.com/plotly/dash-core-components/blob/1e9abb73a52a793060a83c5f41381228192233a0/src/components/Loading.react.js#L41-L62

Furthermore, in DCC 1.9.0, a `className` **is** applied to this div, so the `/assets` CSS works. But in >= 1.9.1, the `className` does not appear in the DOM, so the `height: 100%` is not applied, and this is the reason for the regresion.

So IMO `style` and `className` should be applied to the outermost container, or (to avoid breaking changes and allow these props to be passed to the Spinner) we should give it props like `parent_style` and `parent_className` as discussed in a related issue re: prop nesting in the DOM here: https://github.com/plotly/dash-core-components/issues/606

**Comment by chriddyp** [comment]
A community member reported issues when they upgraded here: https://community.plotly.com/t/percentage-height-of-dcc-loading-children/42222/2

So it seems like we should revert what `className` _used_ to mean and then introduce a new `parent_className` or `child_className` for whatever the new(er) behavior is.

**Comment by jimhendy** [comment]
Hi,
It sounds like you have a fix for this issue. Will it be pulled soon?
Thanks

**Comment by jimhendy** [comment]
Hi @chriddyp & @wbrgss, sorry to bug you but can you please let us know the plan for this? This issue is stopping us updating which is becoming an increasing problem.
Thanks for your help
