### ISSUE TITLE
[BUG] DatePickerRange doesn't allow full deletion of text input

### ISSUE THREAD

**Issue by harryturr** [plotly/dash-core-components#847]
Cannot have empty input for the `DatePickerRange`. If trying to `select all` then `delete`, the original date repopulates the field. If `deleting` character by character, as soon as the last character is deleted the field is repopulated.
![dprange](https://user-images.githubusercontent.com/36603687/90793351-a14a4080-e2d9-11ea-840f-7abd0cea5e31.gif)
___
I would expect `DatePickerRange` to behave like `DatePickerSingle` does:
![dpsingle](https://user-images.githubusercontent.com/36603687/90793352-a1e2d700-e2d9-11ea-93cf-9d6494675df3.gif)

**Comment by AnnMarieW** [comment]
Actually, it appears that the DatePickerRange is correct.  The default for the `clearable` prop is  False.  When True, it clears the dates as expected.   However, in DatePickerSingle it's possible to clear the date regardless of whether `clearable` is True or False.

Here, you can see that DatePickerRange checks for `clearable` in the onDatesChange function: [code ref](github.com/plotly/dash-core-components/blob/dev/src/fragments/DatePickerRange.react.js#L74) 
But not in DatePickerSingle:  [code ref](https://github.com/plotly/dash-core-components/blob/dev/src/fragments/DatePickerSingle.react.js#L32)

This may also solve [#802](https://github.com/plotly/dash-core-components/issues/802)

![clearable_datepicker](https://user-images.githubusercontent.com/72614349/99590290-61fbc080-29aa-11eb-8123-addf96383044.gif)
