### ISSUE TITLE
better scroll behaviour when changing links

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash-core-components#86]
see https://github.com/ReactTraining/react-router/issues/2019 for reference

right now we just keep the current position on the page rather than scrolling to the very top of the page

**Comment by chriddyp** [comment]
also see https://github.com/taion/scroll-behavior

this might be a candidate for github.com/dash/dash-renderer. might be able to support for scroll on hash urls as well

**Comment by chriddyp** [comment]
Perhaps we can put this in a `componentDidUpdate` method of the `URL` component? If the pathname has changed and the component has updated then the new page content _might_ have finished loading and the content could be ready to scroll.

**Comment by ned2** [comment]
Don't have any feedback on you're suggestions i'm afraid, but just wanted to say that we've run into this as a friction point with an app that we're building, so this improvement would be great. Can certainly help out with testing any proposed fix.

**Comment by valentijnnieman** [comment]
I'm pretty sure I fixed this already (guess I forgot to close this issue) closing this now, if it's still an issue feel free to reopen.
