### ISSUE TITLE
Graph's ScrollZoom not working in Chrome 89.0.4389.82 (64-bit)

### ISSUE THREAD

**Issue by KristerBC** [plotly/dash-core-components#936]
Hi,

After updating Google Chrome, the ScrollZoom is no longer working.
When using a Graph with scattergeo, the scrollZoom only works for one tick and then it reactivate the main scroll(if there is any).

Anyone having a way to resolve this issue?

**Comment by alexcjohnson** [comment]
The issue has been reported in plotly.js and will be addressed there -> https://github.com/plotly/plotly.js/issues/5551
