### ISSUE TITLE
dcc.Input has invalid attributes

### ISSUE THREAD

**Issue by coleweusthem** [plotly/dash-core-components#947]
Following web standards all elements should use the format data-* when using unsupported attributes.

dcc.Input uses 'persisted_props' and 'persistence_type' as attributes, to comply with standards they should be 'data-persisted_props' and 'data-persistence_type'

`<input id="lat_min" type="number" max="90" min="-90" placeholder="Min Latitude" step="5" persisted_props="value" persistence_type="local">`

**Comment by alexcjohnson** [comment]
These attributes shouldn't be attached to the DOM at all #855 #703
