### ISSUE TITLE
Infer default values and accept different options/marks format for dcc.Dropdown, dcc.Checklist, dcc.Slider

### ISSUE THREAD

**Issue by xhlulu** [plotly/dash-core-components#960]
Would it be possible to allow components like `dcc.Dropdown` and `dcc.Checklist` to accept `options` other than a list of dictionaries with a format like `{'label': label, 'value': value}` ? For example:
* A list of values would be preprocessed into to a list of `{'label': value, 'value': value}`
* A dictionary of `key -> val` would be processed into a list of `{'label': key, 'value': value}`.

In a similar fashion, for `dcc.Slider` we could accept alternatives for the `marks`:
* A list of values would be preprocessed into a mapping `{i: str(i) for i in list}`
* `marks=True` when there's a min, max, step value specified would display a mark on every step
* `marks: int = n` would display a mark at every `n` steps (so `{i: str(i) for i in range(min, max, n*steps)}`)

Furthermore, the default for `value` could be improved: when set to `None`/`null`, it would be inferred:
* in the case of dropdown, the first element in `options`
* in the case of checklist, an empty list
* in the case of slider, the middle value
* in the case of range slider, it would be the entire range
* etc.

In the case of `dcc.Slider`, when the min and max are left as `None`/`null`, they could also be assigned to the small and largest values in `marks`, or 0 and 100 (and step to 1) if `marks` is not specified.

Overall this is just an idea but it would make the UX much nicer on the python side. Right now to define a slider we need:

```python
my_slider = dcc.Slider(id='slider', min=0, max=10, step=2, value=5, marks={i: str(i) for i in range(0, 11, 2)})
```

With inferred default and polyvalent marks:
```python
my_slider = dcc.Slider(id='slider', min=0, max=10, step=2, marks=True)
# assuming an order:
my_slider = dcc.Slider(id='slider', 0, 10, 2, marks=True)
# equivalent to:
my_slider = dcc.Slider(id='slider', marks=range(0, 11, 2))
```

Similarly for a dropdown:
```python
my_lst = [...]
my_dropdown = dcc.Dropdown(options=[{'value': x, 'label': x} for x in my_lst], value=my_lst[0])
```

which could simply be
```python
my_dropdown = dcc.Dropdown(my_lst)
```

And in the case where we want to access a dataframe column's unique values (super frequent use case for me):
```python
# before
my_dropdown = dcc.Dropdown(
    [{'value': x, 'label': x} for x in df.my_col.unique().tolist()], 
    value=df.my_col.unique().tolist()[0]
)

# after
my_dropdown = dcc.Dropdown(df.my_col.unique().tolist())

# and if we add some helper to handle pandas behind the scene:
my_dropdown = dcc.Dropdown(df.my_col.unique())
```

Obviously sometimes a mapping would work better, but in that case a key-value pair would be more concise than writing "label" and "value" many times:
```python
# before
dcc.Dropdown(
    options=[
        {'label': 'New York City', 'value': 'NYC'},
        {'label': 'Montreal', 'value': 'MTL'},
        {'label': 'San Francisco', 'value': 'SF'},
    ],
    value='MTL',
    clearable=False
) 

# after
dcc.Dropdown(
    {"New York City": "NYC", "Montreal": "MTL", "San Francisco": "SF"},
    clearable=False
) 
```

**Comment by xhluca** [comment]
Some more thoughts and trying to gauge interest on that (please use 👍  or 👎 )

Would `pydata` compatibility benefit the dash user experience? i.e.
```
DataTable.from_dataframe(df, id="my-id")
Slider.from_array(np.array(...))
Download.from_pillow(Image.open(...))
```

**Comment by jackparmer** [comment]
Based on Slack conversations in #dash-labs, here are the optional "shorthands" that we're going to offer for Dash Core components (dcc) and the DataTable (dt) component, illustrated through a series of "hello world" basic Dash apps. Please compare the current syntax with the optional, new shorthand syntax:

Current dcc syntax: https://gist.github.com/jackparmer/864545d0c7f7596ed6b4c9b18a3b252c

Proposed shothand dcc syntax: https://gist.github.com/jackparmer/e777629e0d2ad6b7eae0c07ccc984f75

All of these "hello world" Dash examples can be found by searching here: 
https://dash.gallery/python-docs-dash-snippets/ 
(for example, enter "Legend" to get the radio button example, etc).

**Comment by alexcjohnson** [comment]
Closed by https://github.com/plotly/dash/pull/1763
