### ISSUE TITLE
Can't use box/lasso selection as of dash-core-components 0.13.0

### ISSUE THREAD

**Issue by slishak** [plotly/dash-core-components#97]
I decided to update to the latest version of Dash and all related components, and I lost the ability to drag/lasso select. After rolling back each component one by one, I confirmed that updating dash-core-components from 0.12.7 to 0.13.0 (issue still exists in 0.14.0) caused the issue.

When I drag a rectangle, I see the rectangle appear but no points are greyed out outside the rectangle and no callbacks are called.

Unfortunately can't share any code/plots from this application, but if it turns out the functionality should be working for me I'll try and create a reproducible example.

**Comment by chriddyp** [comment]
This seems to work still: https://plot.ly/dash/interactive-graphing

@slishak Is there anything that is different about your example than the one in the docs?

**Comment by slishak** [comment]
I've managed to fix this in my application by using SVG paths instead of a `Scatter` for my lines, so this is no longer holding me back from upgrading dash-core-components.
